### ISSUE TITLE
Looking forward to it!

### ISSUE THREAD

**Issue by zzw-zwzhang** [lucidrains/imagen-pytorch#1]
^_^

**Comment by zimonitrome** [comment]
Lucidrains is doing the any% SOTA implementation speedrun.

**Comment by imasl** [comment]
@lucidrains we believe in you!

**Comment by Cveinnt** [comment]
New release is already now - the efficiency of this man is scary..

**Comment by nousr** [comment]
![here we go again](https://user-images.githubusercontent.com/51308183/170096127-1264aaaf-b70e-4805-a085-cb05cb732ec5.jpg)

**Comment by Mut1nyJD** [comment]
Hmm I guess the only interesting bits are actually the Cascade DDPM and the Efficient-UNet (which I guess is based on EfficientNet) otherwise I hardly see how this is much difference to GLIDE or am I missing something?

**Comment by lucidrains** [comment]
> Hmm I guess the only interesting bits are actually the Cascade DDPM and the Efficient-UNet (which I guess is based on EfficientNet) otherwise I hardly see how this is much difference to GLIDE or am I missing something?

yup, seems to be the story of our times.. bigger language model, cross attention conditioning (with layernorms for stabilization), better noise level conditioning in the SR3. otherwise i think the most interesting finding is the dynamic thresholding. eager to see someone incorporate it into GLIDE and get some anecdata on how well it performs

**Comment by lucidrains** [comment]
@Mut1nyJD yea, it is largely the same, just a bigger language model, and this dynamic thresholding technique (+ other tricks to perfect the cascading DDPM)

**Comment by datasith** [comment]
@lucidrains is both the hero we need and the one we deserve*.

*as big tech continues to incrementally obscure the datasets/architectures/benchmarks of ML advancements. 🙏

**Comment by ninoppp** [comment]
So the goal of this is t have a locally running implementation of Imagen, right? That's awesome.

**Comment by Mut1nyJD** [comment]
> @Mut1nyJD yea, it is largely the same, just a bigger language model, and this dynamic thresholding technique (+ other tricks to perfect the cascading DDPM)

Hmm thank you thought so. I have not read the paper yet will do over the weekend. But I hope it includes a decent ablation study to show what architectural change actually impacts what. I am particular interested what the difference the EfficientNet UNet and the Cascade DDPM makes.

**Comment by Catalyzzt** [comment]
absolute madman, keep it up

**Comment by loboere** [comment]
What date do you estimate we can generate decent images with this?

**Comment by dragen1860** [comment]
CRAZY MAN, congrats!

**Comment by thebrubaker** [comment]
Awesome!!! Thanks for doing this

**Comment by lucidrains** [comment]
pretty much done
