### ISSUE TITLE
StopIteration error thrown in 'Usage' code when calling imagen.sample()

### ISSUE THREAD

**Issue by nancymackenzie** [lucidrains/imagen-pytorch#102]
Running the [Usage code on the main page](https://github.com/lucidrains/imagen-pytorch#usage) results in a StopIteration error during the images block, when calling the imagen.sample() function. This error specifically occurs on the last line, which includes the conditioning scale.

`StopIteration                             Traceback (most recent call last)
----> 6     'fireworks with blue and green sparkles'], cond_scale = 3.) `

Has anyone had this issue or does anyone know what might be causing it?

**Comment by lucidrains** [comment]
@nancymackenzie Hi Nancy! Let me know if 0.19.8 fixes the problem https://github.com/lucidrains/imagen-pytorch/commit/efdf51f87ec4cfadfd8bce1ddd43ac9abaefe450

**Comment by nancymackenzie** [comment]
Yes, that seems to have fixed it! Thank you so much!
