### ISSUE TITLE
What is the purpose of the text mask?

### ISSUE THREAD

**Issue by vedantroy** [lucidrains/imagen-pytorch#103]
Hi! I was wondering what the purpose of the text mask is?
I understand the concept of masking when training a transformer. Is this similar?

**Comment by lucidrains** [comment]
@vedantroy yup, it is exactly like transformers, where you are training on variable length text and do not wish for the padding to be attended to (although attention is so powerful i don't think it even matters if it does attend to padding, it is more keeping with tradition than anything)
