### ISSUE TITLE
What is the trainer data loader expected to return?

### ISSUE THREAD

**Issue by vedantroy** [lucidrains/imagen-pytorch#107]
From browsing through the source, it seems like the trainer data loader must return a tuple with 4 values:

```
('images', 'text_embeds', 'text_masks', 'cond_images')
```

I see why `images`, `text_embeds`, and `text_masks` would be necessary. But do we need to include a value for `cond_images`?
I'm also wondering how this interacts with some your recent commit that makes it unnecessary to pass in a value for the masks.

**Comment by lucidrains** [comment]
`cond_images` was a feature i added for @deepglugs https://github.com/lucidrains/imagen-pytorch/issues/67

so the code actually matches the tensors up in the order of the strings in that tuple

if you return one tensor, it will match it with images. two tensors, and it will be images and text embeddings. three would be images, text embeddings, and text masks

you can always override that tuple of strings too, if you wish to pass some but not others

**Comment by lucidrains** [comment]
i'll write up a short section for it in the readme some time this week. even without any documentation, i think it is sufficient for most of the cases people care about (unconditional, conditional with text, conditional with text and another conditioning image)
