### ISSUE TITLE
Can not load model anymore

### ISSUE THREAD

**Issue by nephi-dev** [lucidrains/imagen-pytorch#109]
Using Version 0.20.7 and model is 0.20.1

ERROR:
```
Error(s) in loading state_dict for ElucidatedImagen:
	Missing key(s) in state_dict: "unets.0.ups.0.3.net.0.weight", "unets.0.ups.0.3.net.0.bias", "unets.0.ups.1.3.net.0.weight", "unets.0.ups.1.3.net.0.bias", "unets.0.ups.2.3.net.0.weight", "unets.0.ups.2.3.net.0.bias". 
	Unexpected key(s) in state_dict: "unets.0.ups.0.3.1.weight", "unets.0.ups.0.3.1.bias", "unets.0.ups.1.3.1.weight", "unets.0.ups.1.3.1.bias", "unets.0.ups.2.3.1.weight", "unets.0.ups.2.3.1.bias".
```

**Comment by nephi-dev** [comment]
using `pixel_shuffle_upsample=False` in the unets actually works, thanks, this should be set to False by default then? Or is supposed to use the suffle by default?

**Comment by lucidrains** [comment]
@nephi-dev haha, yea, you'll want to retrain with that set to `True`, as it fixes a checkboard artifact issue with the default upsampler

**Comment by nephi-dev** [comment]
Still training, but at moment good results at all, I will try to create another model with this set to True, and check the results thanks
