### ISSUE TITLE
Elucidated.Sample() missing use_tqdm argument?

### ISSUE THREAD

**Issue by trufty** [lucidrains/imagen-pytorch#111]
Get `TypeError: sample() got an unexpected keyword argument 'use_tqdm'` when using Elucidated and attempting to sample with the latest version.

I see that `Imagen.Sample()` does have that parameter.   Is it just missing in Elucidated?

**Comment by lucidrains** [comment]
@trufty https://github.com/lucidrains/imagen-pytorch/commit/4dc1f5d335e5cf0a66c17a13cda31ceb5b3a9537 :pray:

**Comment by lucidrains** [comment]
@trufty so Elucidated is the way to go? seems like everyone is playing around with it

**Comment by lucidrains** [comment]
i want to play around with it :cry:
