### ISSUE TITLE
Set "stop_at_unet_number" based on the unet being trained

### ISSUE THREAD

**Issue by trufty** [lucidrains/imagen-pytorch#112]
Just a suggestion: 
If I am training the first Unet with `only_train_unet_number = 1`, I probably don't want to see the output for unet2 or unet3 when sampling right?  I ended up setting `trainer.Sampling.stop_at_unet_number == only_train_unet_number`  But this would be nice to have by default.

If we should not include the second Unet when training only the first.  An assert might be useful here.  But I'm not really sure what a normal workflow would be with this new architecture.

I just spent way too long trying to figure out why my output was always static :(, and it was because my second untrained Unet was being sampled as well.

**Comment by lucidrains** [comment]
@trufty added a warning for now https://github.com/lucidrains/imagen-pytorch/commit/1fe5fc6c437a1dacb47587caa4e71c0746bda97c i'll look into some better defaults this weekend!
