### ISSUE TITLE
can't pass text in with dataloader and step_with_dl_iter 

### ISSUE THREAD

**Issue by jacobwjs** [lucidrains/imagen-pytorch#113]
hi phil, i'm working with latest version (0.22.9) using the abstracted training and dataloader. seems like it's not possible to pass in raw text (currently needed due to on-the-fly augmentations I'm doing).

https://github.com/lucidrains/imagen-pytorch/blob/1fe5fc6c437a1dacb47587caa4e71c0746bda97c/imagen_pytorch/trainer.py#L465-L466

missing option for `texts` here,
https://github.com/lucidrains/imagen-pytorch/blob/1fe5fc6c437a1dacb47587caa4e71c0746bda97c/imagen_pytorch/trainer.py#L203

based on readme here (https://github.com/lucidrains/imagen-pytorch#dataloader) it seems like order matters? would it be better to require dataloaders return a `dict` with proper key:values for training setup (e.g. unconditional -> {'images': imgs}, text-conditional -> {'images': imgs, 'texts': txts}, etc.). 

with that change stepping turns into below and is guaranteed to adhere to imagen's forward signature,

```
def step_with_dl_iter(self, dl_iter, **kwargs):
        model_input = next(dl_iter)
        # perhaps insert an assert here ensuring model_input.keys() are valid
        loss = self.forward(**{**kwargs, **model_input})
        return loss

```

**Comment by lucidrains** [comment]
@jacobwjs ohh, sorry misread your issue

there's another issue, where i believe if you use accelerator's prepare function, the raw text collating no longer works (but check with Aidan at dalle2-pytorch with that)

you can always just change the order of the keys to whatever you want `dl_tuple_output_keywords_names = ('images', 'text', 'cond_images')` as an example
