### ISSUE TITLE
What is the correct way to pad embeddings / masks?

### ISSUE THREAD

**Issue by vedantroy** [lucidrains/imagen-pytorch#114]
Hi! I've been working on pre-generating embeddings / masks. Here's a quick example:

```
torch.Size([1, 22, 768]) torch.Size([1, 22]) 101
torch.Size([1, 135, 768]) torch.Size([1, 135]) 361
torch.Size([1, 105, 768]) torch.Size([1, 105]) 302
```
This is the output from calling `t5_encode_text("a random string")` on 3 different strings.

- Left column = shape of the embedding tensor
- Middle column = shape of the mask tensor
- Right column = length of the original string

I was wondering, if I want to pass these embeddings / masks to the `ImagenTrainer` as a single batch, would the right thing be to zero-pad the tensors to get the following result:

```
torch.Size([1, 135, 768]) torch.Size([1, 135])
torch.Size([1, 135, 768]) torch.Size([1, 135])
torch.Size([1, 135, 768]) torch.Size([1, 135])
```

I wouldn't zero pad the second row of tensors, since it's the largest.

2 asides:
- I'm assuming the second number in the shapes represents the number of tokens returned from the tokenizer?
- It seems like `t5_encode_text` can accept a string or an array of strings?

**Comment by lucidrains** [comment]
yup, this is correct! you can even omit the mask now, and as long as the text embeddings are zero padded, it will derive the mask at runtime
