### ISSUE TITLE
Attention after each resblock vs attention once per block

### ISSUE THREAD

**Issue by KhrulkovV** [lucidrains/imagen-pytorch#116]
Hello once again!

Currently in code there is only one attention block per each spatial resolution group coming after all resblocks. In guided diffusion (and I traced it back to the original DDPM) there seems to be an attention block after each residual block. However, in the efficient u-net illustration from imagen there is also only one attention block per spatial size.  So perhaps the latter (RB-RB-RB-SA) is the case for efficient u-nets and former (RB-SA-RB-SA) is the case for the standard u-net? Its unlikely that they changed guided-diffusion Unet for the main 64x64 ddpm. However, it is not clear whether it's a mistake in efficient u-net illustration or by design (I think this is the case since it saves a lot of memory).

**Comment by lucidrains** [comment]
@KhrulkovV haha yea, can't find it :disappointed: there's too many vision transformer paper to keep track of

i'll send you an email once i recall the title and find the arxiv link

for now, you can add more attention layers per stage https://github.com/lucidrains/imagen-pytorch/commit/31f5eb5e12618f9b83f24d1dc486d3fe9e07403e#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R1064 just trust me, it is better to have attention at the end :smile: i know this area well

**Comment by KhrulkovV** [comment]
> @KhrulkovV haha yea, can't find it 😞 there's too many vision transformer paper to keep track of. it was a paper investigating hybrid cnn / attention networks for vision, and had a lot of experiments comparing different placements of the transformer blocks relative to convolutional ones
> 
> i'll send you an email once i recall the title and find the arxiv link
> 
> for now, you can add more attention layers per stage in v0.25.0 [31f5eb5#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R1064](https://github.com/lucidrains/imagen-pytorch/commit/31f5eb5e12618f9b83f24d1dc486d3fe9e07403e#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R1064) just trust me, it is better to have attention at the end 😄 i know this area well

Gotcha, thanks! Will try it with attention in the end then!

**Comment by lucidrains** [comment]
@KhrulkovV do let me know if your experiments show different though! i've often felt confident about some part of this phenomenon only to be proven wrong

none of us really have the full picture of what's going on :laughing:

**Comment by lucidrains** [comment]
my current intuition is that convolutions are high pass filters while attention is low-pass. Convolutions focus on the texture in earlier layers and attention synthesizes the extracted features into an understanding of objects and their relations in later ones
