### ISSUE TITLE
Why do you add the low_cond_imgs before the final layers?

### ISSUE THREAD

**Issue by BIGJUN777** [lucidrains/imagen-pytorch#117]
Hi there,

I saw you concat the low_cond_imgs before the final layers in the current version 1b2e86617747d06654c769acf6bcedbb3759cb5b. Does it improve the upscale performance?

**Comment by lucidrains** [comment]
it may not be necessary

as some papers have shown, [adding more skip connections](https://arxiv.org/abs/2102.04306) may not always help

i was trying to resolve an issue with the upsampler over at DALLE2, and thought it may be a good idea, but i may remove it in the next version

**Comment by BIGJUN777** [comment]
Got it. BTW, I wonder what you want to solve by adding this. Can you get me a link to that issue?

**Comment by lucidrains** [comment]
it was for this issue https://github.com/lucidrains/DALLE2-pytorch/pull/181 , but seems to be resolved after prolonged training

**Comment by BIGJUN777** [comment]
Thanks
