### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by fuck-capitalism** [lucidrains/imagen-pytorch#12]
```
RuntimeError: CUDA out of memory. Tried to allocate 258.00 MiB (GPU 0; 2.00 GiB total capacity; 1.01 GiB already allocated; 55.91 MiB free; 1.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Anyone know how to fix?

**Comment by taoisu** [comment]
Your gpu memory is not enough, try cpu

**Comment by lmoroney** [comment]
How big a GPU have you tried it with? 

Also -- how many iterations of the loss=imgen / loss.backward() loop do you need to get results?

One run through, I get noise
Two runs through, my 16Gb GPU runs out of memory

**Comment by lucidrains** [comment]
at least 2~3 million steps

you can set `max_batch_size` on the trainer forward to a low number (1 is the lowest) and see if that helps

**Comment by lmoroney** [comment]
ANy particular recommended GPU? Have you tried it with the GPU in colab?

**Comment by lucidrains** [comment]
@lmoroney i'll be making an unconditional port (text-less) and you'll be able to train with just `imagen-trainer --data ./path/to/images`

**Comment by lmoroney** [comment]
Cool, I'll look out for it :)

**Comment by lucidrains** [comment]
@lmoroney one of the findings in the paper is that the image neural network doesn't even have to be that big - most of the heavy lifting is done by the pretrained attention network (T5)
