### ISSUE TITLE
lowres_cond_img not normalized when sampling with elucidated_imagen

### ISSUE THREAD

**Issue by Sys-if** [lucidrains/imagen-pytorch#124]
Hi,
First, thank you for your work!
I noticed that `one_unet_sample()` unnormalize the images  in its output but `lowres_cond_img` isn't normalized in `sample()`. I added `lowres_cond_img = maybe(self.normalize_img)(lowres_cond_img)` after resizing to solve this, like you did in `forward()`.

**Comment by lucidrains** [comment]
@Sys-if oh yes, you are right, thank you! https://github.com/lucidrains/imagen-pytorch/commit/30d67044e92609bff05f852dcd26f1154b99aab5
