### ISSUE TITLE
Sweep over conditioning noise?

### ISSUE THREAD

**Issue by abhay-agarwal** [lucidrains/imagen-pytorch#126]
Hey, I am just reviewing this library and comparing it to the published paper. I was a bit confused by the code after reading this:

> Given a conditioning low-resolution image and augmentation level (a.k.a aug_level) (e.g., strength of Gaussian noise or blur), we corrupt the low-resolution image with the augmentation (corresponding to aug_level), and condition the diffusion model on aug_level. During training, aug_level is chosen randomly, while during inference, we sweep over its different values to find the best sample quality. In our case, we use Gaussian noise as a form of augmentation, and apply variance preserving Gaussian noise augmentation resembling the forward process used in diffusion models (Appendix A). The augmentation level is specified using aug_level ∈ [0, 1]. See Fig. A.32 for reference pseudocode.

What do they mean by sweep over the different values? In this repo, it seems like you do not do that, or if you do, how do you define the 'best' sample quality? Maybe I am misunderstanding this section entirely?

**Comment by abhay-agarwal** [comment]
https://github.com/lucidrains/imagen-pytorch/blob/8669a8eccf659671c9018a07adb8fa9c4cf95bde/imagen_pytorch/imagen_pytorch.py#L1688

The comment here mentions that at sample time, you fix the `aug_level` rather than sweep. But I wasn't able to 100% discern that from the code.

**Comment by lucidrains** [comment]
It just means they did a hyperparameter sweep, which you can do as well with that parameter you found (can also be overridden when calling sample)

If you look in the appendix, they mentioned their ideal value was 0.2

**Comment by abhay-agarwal** [comment]
Got it, didn't see those two graphs on the first read. Thanks!
