### ISSUE TITLE
about training images

### ISSUE THREAD

**Issue by titi-Yu** [lucidrains/imagen-pytorch#130]
for :

train_dl = get_images_dataloader('/path/to/training/images', batch_size=16, image_size=128)

 i am the beginner of image field, sorry about that, may i ask for this 【training images】dataset ?

**Comment by jacobwjs** [comment]
This is up to you to define friend.

**Comment by titi-Yu** [comment]
> This is up to you to define friend.

![image](https://user-images.githubusercontent.com/51437324/179717211-e859bd10-c097-4131-8889-d00587776163.png)

but how can i save this image, not only image.shape ?

**Comment by jacobwjs** [comment]
@titi-Yu I think you might be confused. Those values are just to highlight the training procedure and are nothing but noise at this point.

If you wanted to save them (easily) for some reason you need to pass an extra argument to sample() (i.e. return_pil_images = True if I recall from memory).

You'll have to train on a dataset if you want to produce anything more than noise. See the link lucidrains pointed you to.
