### ISSUE TITLE
Resume training uses way more VRAM than fresh training, triggering OOM

### ISSUE THREAD

**Issue by trufty** [lucidrains/imagen-pytorch#131]
Hey again!

I noticed that after trying to resume my training (v1.0.0) I was getting OOM, but this was the same checkpoint I was just training on minutes earlier.

Here's a minimal example that triggers OOM.  Run it once to generate the checkpoint and run it again to OOM.
You may have to adjust it to your own VRAM limits (i'm using a 3090)
```py
# Run once to generate checkpoint. VRAM sitting at a safe 21/24GB
# Run again to load from existing checkpoint causing OOM


import torch, os
from imagen_pytorch import BaseUnet64, SRUnet256, ImagenTrainer, ElucidatedImagen
from imagen_pytorch.data import Dataset

checkpoint = "./checkpoint.pt"
img_path = "../images/"
train_unet_num = 1
img_size = 64
batch_size = 128
max_batch_size = 16

unet1 = BaseUnet64(
    dim = 256,
)

unet2 = SRUnet256(
    dim = 128,
)

imagen = ElucidatedImagen(
    unets = (unet1, unet2),
    image_sizes = (64, 256),
    num_sample_steps = (19, 19),
    condition_on_text = False
)

print('Starting DataLoader')
data = Dataset(img_path, image_size = img_size)
dl = torch.utils.data.DataLoader(data,
                                batch_size=batch_size,
                                shuffle=True,
                                num_workers=8)

trainer = ImagenTrainer(
    imagen,
    train_dl = dl,
    use_ema = False,
    only_train_unet_number = train_unet_num
).cuda()


if os.path.exists(checkpoint):
    print('Loading existing checkpoint')
    _ = trainer.load(checkpoint)
    last_step = _['steps'][train_unet_num - 1]


print('Training')
for i in range(2):
    loss = trainer.train_step(unet_number = train_unet_num, max_batch_size = max_batch_size)

print('Saving')
trainer.save(checkpoint)

```

If you see anything obviously wrong here, let me know.
Thanks!

**Comment by jacobwjs** [comment]
@trufty hi have you tried mapping to cpu first and then pushing to your gpu?

you'd need to alter the trainer to something along the lines of,
`loaded_obj = torch.load(str(path), map_location = 'cpu')`

find call here, https://github.com/lucidrains/imagen-pytorch/blob/64e183dd036ab60e0c052bb672746a4150dd4f18/imagen_pytorch/trainer.py#L592


another sanity check is there are no orphaned processes hanging around capturing CUDA mem.

**Comment by jacobwjs** [comment]
@trufty hmm strange. I'm sitting at about the same amount of free vram as you (about 2GB free) and able to train, checkpoint, load and continue training.

this is with __version__ = '1.0.2' however, but hadn't run into issues before this either.

if I think of anything i'll drop a message here.

on a side note, why `num_sample_steps = (19, 19)`? is this something you found beneficial, or just random?

**Comment by jacobwjs** [comment]
> If you were to restart training from scratch without an existing checkpoint, do you see a drop in total memory usage too?
> 
> (19, 19), or (19, 35) was recommended on the LAION discord, and the results seem fine at that time-step for Elucidated. (still need to try the SRUnet though)

not sure I follow. restart from scratch... so just start training? 

i do see various fluctuations in the beginning as things are getting pushed across the bus and vram starts filling up, but nothing out of the ordinary. i haven't really looked into though.

are you seeing large fluctuations?

I created a few unit tests that load various unet/imagen configs and fake data to get a rough idea of batch/model size my machine can tolerate. basic idea is to train a few steps, save, load, train next unet a few steps... repeat. i've been using it to make sure when I do kick off a real training session i'm not screwed later. perhaps something similar would be informative in tracking down this issue.
