### ISSUE TITLE
removing discrete ddpm

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/imagen-pytorch#133]
is anyone using the discrete time gaussian diffusion?

i'm thinking about removing it just to keep the repository from getting too complex

**Comment by Mut1nyJD** [comment]
What's the benefit of discrete time gaussian diffusion compared to normal again?

**Comment by lucidrains** [comment]
@Mut1nyJD afaict there is no advantage other than being able to cache some calculations

**Comment by Mut1nyJD** [comment]
@lucidrains 

So it might be marginal faster when sampling? Hmm not sure if it is worth keeping

**Comment by lucidrains** [comment]
@Mut1nyJD yea i think i'll remove it then!

**Comment by vedantroy** [comment]
From my understanding, normal gaussian diffusion refers to the diffusion process in: https://arxiv.org/pdf/2107.00630.pdf (variational diffusion models) whereas discrete gaussian diffusion refers to the process in: https://arxiv.org/pdf/2102.09672.pdf (improved ddpm).

As far as I can tell, variational diffusion models optimize for likelihood:
> Here, we
> optimize for likelihood, which is sensitive to fine scale details and exact values of individual pixels.

however, this might come at the cost of image quality?
