### ISSUE TITLE
when training unet 2, unet 1 only produce noise despite training

### ISSUE THREAD

**Issue by deepglugs** [lucidrains/imagen-pytorch#138]
Observing something strange while trying to train unet 2.  First, while training unet1, my samples seem nominal:
![unet1](https://user-images.githubusercontent.com/70453896/180060448-d0d76c73-39be-48ef-9c75-005d217022fa.png)

However, once I start training unet2, it appears unet1 is producing only noise:
![unet2](https://user-images.githubusercontent.com/70453896/180060520-33aa025f-266e-449f-b40a-ff0ce958519e.png)

To make matters more strange, once I start training unet3, both unet1 and unet2 seem fine:
![imagen_1_2](https://user-images.githubusercontent.com/70453896/180060602-b12b6157-eacc-4f76-b5a6-66086d59b420.png)

Using ElucidatedImagen.  My training script is here: https://github.com/deepglugs/deep_imagen/blob/main/imagen.py

**Comment by lucidrains** [comment]
@deepglugs instead of using `load_imagen_from_checkpoint`, could you instead use `trainer.load`

that function is actually designed for fine-tuning, and loads the exponentially moving averaged networks into the main network for further training

**Comment by lucidrains** [comment]
ok, i really have to focus on attention today, be back on Friday!

**Comment by lucidrains** [comment]
@deepglugs on Friday, i'll take care of auto-checkpointing too, by passing in `checkpoint_folder` and `checkpoint_every` to the `ImagenTrainer`

**Comment by deepglugs** [comment]
> @deepglugs instead of using `load_imagen_from_checkpoint`, could you instead use `trainer.load`
> 
> that function is actually designed for fine-tuning, and loads the exponentially moving averaged networks into the main network for further training

During training I am using Trainer.load: https://github.com/deepglugs/deep_imagen/blob/main/imagen.py#L287

**Comment by lucidrains** [comment]
@deepglugs hmm, i'm not sure what's going on! let's keep it open and see if there are other researchers facing the same issue. i'll reexamine your script on Friday morning

**Comment by lucidrains** [comment]
what is `unet1_dims` https://github.com/deepglugs/deep_imagen/blob/main/imagen.py#L387

**Comment by ryudrigo** [comment]
I used the scripts from deepglug's repository and could not reproduce the problem

**Comment by lucidrains** [comment]
@ryudrigo thanks!

**Comment by deepglugs** [comment]
Looks like it was something with that one particular trained model.  I started a new one last night and it appears to be working fine.  Will close.
