### ISSUE TITLE
What were the dimensions of the images they used to train the text => image model in the paper?

### ISSUE THREAD

**Issue by vedantroy** [lucidrains/imagen-pytorch#139]
Hi!

I've been reading through the Imagen paper. Specifically, I've been trying to figure out what image sizes they used to train the the initial text => 64x64 image model.

I've been training on images with dimensions 256x256, because the lower the dimensions the more blurry the input is.
But, given that the text => image model is probably designed to generate blurry images, it might make sense to train on 64x64 resized images instead.

However, I can't find a mention in the paper of what the dimensions were of the images they trained on for the text => image model.
Would you happen to know?

**Comment by vedantroy** [comment]
> Not sure about the paper but in `trainer.forward()` you images are being resized anyway
> 
> https://github.com/lucidrains/imagen-pytorch/blob/51f39b93670b17c803e7189ee0492585b30935f8/imagen_pytorch/imagen_pytorch.py#L2360

Good catch!

**Comment by lucidrains** [comment]
@vedantroy yup, as trufty noticed, as long as you pass in images that are bigger than the maximum dimensions of the image being produced by the entire cascade, you are fine

it will resize all the images internally
