### ISSUE TITLE
Train only one unet at time

### ISSUE THREAD

**Issue by nephi-dev** [lucidrains/imagen-pytorch#142]
In respect to [this line](https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/trainer.py#L802). How can I train with two(or more) unets, one per time?

**Comment by lucidrains** [comment]
@nephi-dev you'll need to save the checkpoint, and resume training in a new script, like what is done here https://github.com/lucidrains/imagen-pytorch/issues/138

```bash
$ python train.py --unet 1
```

then after some training

```bash
$ python train.py --unet 2
```

**Comment by nephi-dev** [comment]
thanks, I'll try

**Comment by lucidrains** [comment]
@nephi-dev

yea, give me until next week, and i'll have a auto-checkpointing system in place

```python
trainer = ImagenTrainer(
  ...
  checkpoint_path = './checkpoints/',
  checkpoint_every = 1000 # checkpoint every 1000 steps
)
```

**Comment by lucidrains** [comment]
@nephi-dev decided to just build it today and get it out of the way, let me know if it works!

**Comment by nephi-dev** [comment]
@lucidrains oh, nicee, I'm already using the one i've build, if something breaks here, i'll jump to yours
