### ISSUE TITLE
Why 8 attention heads rather than 4 for BaseUnet64?

### ISSUE THREAD

**Issue by vedantroy** [lucidrains/imagen-pytorch#145]
Hi! The text => image UNet in the Imagen paper follows the UNet architecture defined in [Improved Denoising Diffusion Probabilistic Models](https://arxiv.org/pdf/2102.09672.pdf).
In that paper, they use 4 attention heads:
![image](https://user-images.githubusercontent.com/8407819/180629651-24f56464-272c-4226-b3da-f07902edc4be.png)

In the `BaseUnet64`, the # of attention heads is set to 8:
https://github.com/lucidrains/imagen-pytorch/blob/2535012168d8839130af9c2b61ae17d6df3a7064/imagen_pytorch/imagen_pytorch.py#L1712

Is this b/c more attention heads = generally better?

The entire thing is a bit confusing, b/c the Imagen paper doesn't specify the number of heads. Rather, it specifies the number of channels per head. This indicates to me that layers near the bottom of the UNet would have more attention heads since they would have a greater amount of channels, which is a deviation from OpenAI's UNet architecture that the Imagen paper claims to follow. Not sure what's going on there.
![image](https://user-images.githubusercontent.com/8407819/180629722-5941af7c-bbfe-43a0-b85a-90afac14b187.png)

**Comment by lucidrains** [comment]
yup, more heads the better! 8 heads with dimension 64 is on the high end, while 4 heads and dimension of 32 on the low

**Comment by vedantroy** [comment]
> yup, more heads the better! 8 heads with dimension 64 is on the high end, while 4 heads and dimension of 32 on the low

I think this means the `BaseUnet64` does diverge somewhat significantly from the Imagen UNet then, right?
B/c (In the Imagen UNet):
- At resolution 32x32, num_channels will be `512 * 2 = 1024`, so `num_heads = 1024/64 = 16`
- At resolution 16x16, num_channels will be `512 * 3 = 1536`, so `num_heads = 1536/64 = 24`
- At resolution 8x8, num_channels will be `512 * 4 = 2048`, so `num_heads = 2048/64 = 32`.

Whereas, in `BaseUnet64`, the number of heads will always be 8, right?

**Comment by lucidrains** [comment]
no it is still pretty similar

they hold the number of attention heads constant at 4, with dimension of 64, so you would project from model dimensions to 256

**Comment by lucidrains** [comment]
haha this detail doesn't matter that much. if you really want to, you can try increasing heads to 12 or 16, but you will see diminishing returns

**Comment by vedantroy** [comment]
> no it is still pretty similar
> 
> they hold the number of attention heads constant at 4, with dimension of 64, so you would project from model dimensions to 256

Ahhh, that's the thing I was missing. They are projecting from the model dimensions to 256. Got it got it! Thanks for clarifying.
