### ISSUE TITLE
Elucidated inpainting last step flag

### ISSUE THREAD

**Issue by flavioschneider** [lucidrains/imagen-pytorch#146]
Hi @lucidrains! I might be mistaken, but isn't [this](https://github.com/lucidrains/imagen-pytorch/blob/2d938f4e12b8468180613ff2b669bd6c1e4fd8b0/imagen_pytorch/elucidated_imagen.py#L405) flag active the first step of the denoising process, instead of the last (since `enumerate` is used)?

**Comment by lucidrains** [comment]
@flavioschneider no you are absolutely correct Flavio! thank you! https://github.com/lucidrains/imagen-pytorch/commit/fac59d7b8d0aabbb41f75085a927c978b9984a2f
