### ISSUE TITLE
checkpointing to Backblaze b2

### ISSUE THREAD

**Issue by Birch-san** [lucidrains/imagen-pytorch#153]
heyo, thanks for adding checkpointing support for Google Drive and S3. 🙂 

[Backblaze B2](https://www.backblaze.com/b2/cloud-storage.html) is a super cheap storage backend (both storage and download are about 80% cheaper than S3).  
it has a [Python SDK](https://github.com/Backblaze/b2-sdk-python).

I'm not sure how difficult it would be to integrate it compared to the others, but the pricing is appealing.

**Comment by lucidrains** [comment]
@Birch-san you'll have to write your own adapter that is compliant with fsspec https://filesystem-spec.readthedocs.io/en/latest/ then you can just pass in the instance with this keyword arg https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/trainer.py#L257

**Comment by srelbo** [comment]
hey @Birch-san , we use Backblaze for our work and it works great! Also much cheaper than others and we get CDN from [CloudFare](https://help.backblaze.com/hc/en-us/articles/217666928-Using-Backblaze-B2-with-the-Cloudflare-CDN)

We can open source some of our code, that does file uploads (multi-part and really large file uploads), but it will take us a week or so to get to it.

**Comment by rom1504** [comment]
https://www.backblaze.com/b2/docs/s3_compatible_api.html backblaze has a S3 compatibility layer, so you can already use it with imagen-pytorch (fsspec supports S3)

**Comment by Birch-san** [comment]
Thanks all! Using via S3 compatibility layer sounds perfect; will try that once I get to training.
