### ISSUE TITLE
error when instantiating ImagenTrainer

### ISSUE THREAD

**Issue by nephi-dev** [lucidrains/imagen-pytorch#154]
![image](https://user-images.githubusercontent.com/48372168/181284551-887ef1b2-f678-4600-9b3f-02cd3b5f9c1d.png)

**Comment by lucidrains** [comment]
@nephi-dev ohh oops! https://github.com/lucidrains/imagen-pytorch/commit/ea415c5bca2604756c4d2b1eafebe2fc4d516505 :pray:

**Comment by nephi-dev** [comment]
tks
