### ISSUE TITLE
Can't see generated image in colab

### ISSUE THREAD

**Issue by jessyseonoob** [lucidrains/imagen-pytorch#16]
Hi,

First, great work !
I've tried to create a colab, 
i've copy paste your code.
all runing well, but it seem it don't display the generated image at the end. 
I am missing something ? 

thanks

![Screenshot_2022-05-28-20-12-54-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/7141139/170837959-ea44cd55-aaef-4f90-a10a-a01f530c65b8.jpg)

**Comment by Mimocro** [comment]
Did you try 
```
from IPython import display
display.Image(images)
```
Also why images and not images[0] or images[1]?

**Comment by woctezuma** [comment]
- #4

**Comment by phibosGit** [comment]
Jupyter Colab?

You can post the file?
My problem is GPU Driver

**Comment by johnpaulbin** [comment]
> Hi,
> 
> First, great work ! I've tried to create a colab, i've copy paste your code. all runing well, but it seem it don't display the generated image at the end. I am missing something ?
> 
> thanks
> 
> ![Screenshot_2022-05-28-20-12-54-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/7141139/170837959-ea44cd55-aaef-4f90-a10a-a01f530c65b8.jpg)

Hi, you might be new here: Your images will be shown as random noise since you are not using any pre trained model (as of writing this, there is none yet)

**Comment by dragen1860** [comment]
`print(images)` will only show the raw number of pixels. you need to matplotlib show or cv2.show image.

**Comment by woctezuma** [comment]
Or [`google/mediapy`](https://github.com/google/mediapy).

**Comment by lucidrains** [comment]
@jessyseonoob you can always just set a https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L1431 `return_pil_images = True` on forward, and it'll return the pillow images, for saving or displaying

**Comment by lucidrains** [comment]
but yea, you may want to actually train the artificial neural network on Laion5B first..
