### ISSUE TITLE
MAYBE BUG in sample: add noise first to lowres_con_img, then do normalize_img

### ISSUE THREAD

**Issue by animebing** [lucidrains/imagen-pytorch#160]
In the training phase, I found that for `lowres_con_img`, `normalize_img` is first done, then add noise to it, but in the sampling phase, the process is reversed, I don't know it is a bug or something I misunderstand, thanks.

**Comment by lucidrains** [comment]
@animebing Hi Bingbing! You are absolutely correct there was a bug in the non-elucidated version of Imagen and I (and everyone else) thank you for it! https://github.com/lucidrains/imagen-pytorch/commit/3a35e8a3df853d2cc85a93ea33b524e075dde16f

**Comment by animebing** [comment]
:clap:
