### ISSUE TITLE
NaN error with low number of timesteps

### ISSUE THREAD

**Issue by oconnoob** [lucidrains/imagen-pytorch#161]
Hey there!

I've found a small issue, although I'm not sure that it is still relevant (it looks like discrete time diffusion was removed and only continuous time diffusion remains as an option?) Regardless, I was using the discrete time diffusion schedule `GaussianDiffusion` and running into NaN results from `q_sample`, which stemmed from NaN values in `sqrt_alphas_cumprod`, which in turn stemmed from negative values in `alphas`, which in turn stemmed from some values of beta being greater than 1.

I was using a linear schedule from 0.0001 to 0.02 (the DDPM default) but was only using 10 timesteps (for testing), so when multiplying the final beta value 0.02 by the scale value `scale=1000/timesteps`, the final beta value was greater than 1.

The scale must be less than 50, **meaning that the number of timesteps must be greater than 20**, to avoid this issue, but of course this only works with the default 0.02 ending beta value and will change if not using the default.

If the `GaussianDiffusion` class is still being used, perhaps we could incorporate a way of capping the value of `scale` to avoid this issue (or something smarter)?

Thanks!

P.S. - thanks @lucidrains for creating this project. I've gone through every line and can't emphasize how great it is for the community to have this open-source implementation to play with and utilize. I've learned a lot reading through it!

**Comment by lucidrains** [comment]
@oconnoob thanks! the aim is to demystify, so glad you found it educational :smile: 

and yea, i've removed the discrete gaussian diffusion to keep the repository readable, but i'll definitely add that extra assert in my other repositories where i still use discrete time
