### ISSUE TITLE
Weak or non-functional text conditioning with Imagen vs ElucidatedImagen

### ISSUE THREAD

**Issue by deepglugs** [lucidrains/imagen-pytorch#162]
Ran an experiment last night to see how long it would take for text-conditioning to start showing up with my my 30k "faces" dataset.  With ElucidatedImagen, it took about 7.5 epochs to get "blonde_hair" in the second image from the left.  With Imagen, I was unable to get any blondes after 10 epochs.

Both are sampled with cond_scale=10.0

ElucidatedImagen:
![imagen_8_25_loss0 09128](https://user-images.githubusercontent.com/70453896/182413204-ea8765dd-53ec-4d90-a9a6-221085df17e1.png)

Imagen:
![imagen_10_93_loss0 09803](https://user-images.githubusercontent.com/70453896/182412320-38a4acc4-a631-41e2-8414-f67892f82ce7.png)

configurations:
```python
if not args.no_elu:
        imagen = ElucidatedImagenConfig(
            unets=unets,
            text_encoder_name=args.text_encoder,
            num_sample_steps=sample_steps,
            image_sizes=image_sizes,
            per_sample_random_aug_noise_level=True,
            lowres_sample_noise_level=0.3
        ).create().to(args.device)

    else:
        imagen = ImagenConfig(
            unets=unets,
            text_encoder_name=args.text_encoder,
            noise_schedules=["cosine", "cosine"],
            pred_objectives=["noise", "x_start"],
            image_sizes=image_sizes,
            per_sample_random_aug_noise_level=True,
            lowres_sample_noise_level=0.3
        ).create().to(args.device)
```

**Comment by lucidrains** [comment]
@deepglugs i don't think this is an issue, but more a research finding

**Comment by lucidrains** [comment]
@deepglugs the whole claim of Imagen is that text binding improves with larger attention models, and that cross attention is a critical component

**Comment by tripzero** [comment]
It is more of a research finding... but I wonder how much longer it'd take Imagen to start conditioning on the text.

**Comment by integer753** [comment]
conditioning is working great for me on the regular imagen, i'm on version 0.25.4, one thing i noticed is that i needed enough variety in my descriptions or conditioning wouldn't work
