### ISSUE TITLE
Checkpoint has tripled in size

### ISSUE THREAD

**Issue by integer753** [lucidrains/imagen-pytorch#166]
I went from version 0.25.4 to version 1.5.12 recently, and everything is working great but i've noticed my checkpoints have tripled in size. 
It's making it a lot harder to transfer them to my server. With no changes in configuration, my checkpoint went from 2GB to 6GB.

I narrowed the cause down to the recent changes in the trainer related to the optimizer.

If i remove the optimizer keys from the state dict, my checkpoint goes from 6GB to 2GB again.

I'm using the trainer.load & trainer.save functions usually.

```
chkpnt = torch.load(f"{OUTPUT_FOLDER}/large.pt", map_location='cpu')
del chkpnt["optim0"]
del chkpnt["optim1"]
torch.save(chkpnt, f"{OUTPUT_FOLDER}/reduced.pt")
```
-> 4GB reduction in size

So it's probably related to this change:
https://github.com/lucidrains/imagen-pytorch/commit/1cdd36261b9c16864f9a92f7afc44284b9379315

**Comment by integer753** [comment]
Going by that commit, it seems like the optimiser was just never properly saved in the past. But then i wonder, is the optimiser state dict really that big? Is that normal?

**Comment by lucidrains** [comment]
@integer753 ohh so the reason is, besides the optimizer that you noted, each of the generative neural network also has a corresponding exponentially moving averaged clone. in many settings in machine learning, keeping an exponentially moving averaged version of the main network really helps with final results

**Comment by lucidrains** [comment]
@integer753 what i could do is offer an inference-only checkpoint that only saves the final exponentially moving averaged network, something like `.save(for_inference = True)`

**Comment by integer753** [comment]
sounds great 👍 in any case i think we can close the ticket since it seems like it is al working as intended, i just underestimated the size of the optimiser and didn't realise we weren't saving it before

**Comment by lucidrains** [comment]
@integer753 ok! for starters you can remove optimizer and schedulers from the saved checkpoint with https://github.com/lucidrains/imagen-pytorch/commit/c440a4b029e9c62268a84e30cf1eb7ebdd5de28a#diff-db403ff86c6fb0812b3ce92a98fb7d76cc888c28dfa3e0a5421bde05febd47bbR633 i'll have to think about how to handle the EMA vs non-EMA version of the networks some more
