### ISSUE TITLE
option to replace noise during sample

### ISSUE THREAD

**Issue by deepglugs** [lucidrains/imagen-pytorch#170]
The idea is that it would allow some of the functionality of cond_image without any training.  This has been tested by m9 (discord).

Something like:

```python
imagen.sample(texts, noise=an_image_tensor)
```

**Comment by lucidrains** [comment]
@deepglugs i'm not sure i understand

could you point to the line of code that you are trying to substitute with your own noise. and how does it relate to the conditioning image?

**Comment by deepglugs** [comment]
Afaiu, the cond_image is concatenated onto the noise.  This argument would replace the noise altogether with a "starting image" of sorts.

**Comment by Nodja** [comment]
I've seen this before in other diffusion models and works well, it's usually called init_image, having a skip_steps parameter would also be useful, it would skip the first x steps of sampling.

**Comment by lucidrains** [comment]
@deepglugs ohh got it, but why wouldn't you use the inpainting feature (repaint)? that should work a lot better

**Comment by lucidrains** [comment]
@Nodja ohh cool, i wasn't aware of this technique

you would manually noise the init image and guess at which timestep to start at? that doesn't sound very rigorous

does it work?

**Comment by lucidrains** [comment]
https://github.com/lucidrains/imagen-pytorch#inpainting this should be state of the art for inpainting, if that is what you are trying to achieve

**Comment by lucidrains** [comment]
@Nodja @deepglugs i could add it for exploration purposes i suppose

it is such a young technology, we have no idea what is possible yet

**Comment by lucidrains** [comment]
tell you what, i need to walk Ice Cream and run some errands downtown, but post some of the results that m9 is seeing with this approach (or link me to the paper) and i can start thinking about how to fit in this feature

**Comment by marunine** [comment]
I don't know if there's a paper specifically but I comment on the approach I took in lieu of inpainting, which I couldn't get working with satisfiable results, unfortunately.

https://github.com/marunine/imagen-pytorch/blob/b36bceb853d3110e92332dacf19952068fda7ae9/imagen_pytorch/elucidated_imagen.py#L348

Adds the initial noise onto an initial image. The sigma min/max let you control the sampling scheduling and how much noise ends up getting added onto the image. This leverages the model's ability to denoise images like it does during training but is more flexible than cond_image because you can scale how much of the initial you take based on your sigma max.

I've tried the skip sampling steps out, but determined it wasn't necessary because of the control elucidated gives you. The regular imagen would need it but I haven't tested it.

**Comment by marunine** [comment]
I was under the impression that inpaint should be equivalent to this if you pass all zeroes as the mask, but in my experience I ended up getting gray images or noisy images at 1/5 resample loops.

I didn't carefully review the code to see if there's a bug somewhere in there, but I agree that it should be more fully functional than what I ended up doing.

**Comment by lucidrains** [comment]
@marunine oh, maybe i misunderstood the purpose here

are you trying to lightly condition the generation by giving it a subliminal image at the very start?

**Comment by lucidrains** [comment]
it sounds like it isn't working anyways, so maybe we should not add it

however, let's definitely reopen an issue for inpainting, if repaint is not working as expected

**Comment by deepglugs** [comment]
> it sounds like it isn't working anyways, so maybe we should not add it

Which part isn't working?  the init_image?

**Comment by lucidrains** [comment]
@deepglugs 

> I don't know if there's a paper specifically but I can comment on the approach I took in lieu of inpainting, which I couldn't get working with satisfiable results, unfortunately.

**Comment by marunine** [comment]
> @deepglugs
> 
> > I don't know if there's a paper specifically but I can comment on the approach I took in lieu of inpainting, which I couldn't get working with satisfiable results, unfortunately.

I meant that I couldn't get inpainting to work. The init_images method works better than I expected - it can pick up pose, style, etc based on how much noise you apply through the sigma schedule.

It's a little bit more flexible than the binary mask of the inpainting in that regard, but I think inpainting is the better approach overall provided the implementation works.

**Comment by lucidrains** [comment]
@marunine @deepglugs can you provide some examples of the success you are seeing? seeing is believing

**Comment by marunine** [comment]
![1659986857__2022-08-08T15-27-57](https://user-images.githubusercontent.com/97926137/183500634-31377891-9113-4be1-8649-7eba1b4c3a18.png)
![1659987560__2022-08-08T15-39-42](https://user-images.githubusercontent.com/97926137/183500643-d5f29b14-5acb-496b-8c5d-fd5fe4d58e01.png)

The bottom caption includes 'sketch` as a modifier.

I will take down the top image later as I don't own the copyright.

**Comment by lucidrains** [comment]
@marunine ohhh i see, yea, this type of cartoon image is challenging for inpainting. unless one trains with pretty much the whole internet

**Comment by lucidrains** [comment]
@marunine @deepglugs ok! i'll definitely consider it later this week when i get back to ddpms

thank you for sharing this!

**Comment by Nodja** [comment]
The place I saw init_image used previously was the laion logo generator on replicate [here](https://replicate.com/laion-ai/erlich/versions/4e6131449d7647c78089340ddf01f4218cdedce0e1ff42f99c7046e288298c06), [github repo](https://github.com/LAION-AI/ldm-finetune). (Linking old version of replicate as init_skip_fraction seems to be broken in the newer ones.)

All values left default unless specified. Init image I used is on the left, just something I quickly drew in paint.

### No init image
![image](https://user-images.githubusercontent.com/7379193/183506653-067a0747-4a2d-4980-9b80-5f9f7ac89a02.png)


### Init image with 0.02 init_skip_fraction (doesn't accept 0)
![image](https://user-images.githubusercontent.com/7379193/183507025-5207c58e-9029-4256-ae01-ff8e25645e96.png)


### init_image with 0.1 init_skip_fraction
![image](https://user-images.githubusercontent.com/7379193/183507251-5eddf94f-13bb-45c8-aa42-59813c0af11e.png)


### init_image with 0.2 init_skip_fraction
![image](https://user-images.githubusercontent.com/7379193/183507361-c9f81452-3d1e-4394-b4f1-8604123ea944.png)


### init_image with 0.3 init_skip_fraction
![image](https://user-images.githubusercontent.com/7379193/183507333-1ae67d7d-d47d-4f93-94c2-c58585a1a8d7.png)


As you can see the more steps you skip the bigger the influence the init_image has on the final result, to the point that it's mostly a straight up copy at values above 0.5.

**Comment by lucidrains** [comment]
very cool! maybe you should all write a paper on this haha

at least you can give it a name, once you flesh out this technique some more

ok, be back later this week! it is time to meditate on attention once more..

**Comment by lucidrains** [comment]
ok I'm convinced! I'll add it later this week with credit to whoever discovered this

**Comment by lucidrains** [comment]
for the example above, is the initial imaged normalized to -1 to 1 before summing the noise?

**Comment by Nodja** [comment]
If you're talking about the latent-diffusion demo, [that seems to be the case.](https://github.com/LAION-AI/ldm-finetune/blob/main/guided_diffusion/inpaint_util.py#L228)

**Comment by lucidrains** [comment]
yup, it is appropriately normalized! thanks!

**Comment by lucidrains** [comment]
@deepglugs do you want to see if 1.7.0 works? https://github.com/lucidrains/imagen-pytorch/commit/37953b246f239eb5688344416b65d1e16d0e0289 also welcoming any PRs with a small tutorial on how to use it (and how to effectively choose the number of steps to skip)

**Comment by deepglugs** [comment]
Sure.  I'll give it a shot.

**Comment by deepglugs** [comment]
Looks like there might be a typo in config.py with the 'video' keyword?

```
Traceback (most recent call last):
  File "/home/kev/ai/src/deep-imagen/imagen.py", line 731, in <module>
    main()
  File "/home/kev/ai/src/deep-imagen/imagen.py", line 134, in main
    sample(args)
  File "/home/kev/ai/src/deep-imagen/imagen.py", line 141, in sample
    imagen = load(args.imagen).to(args.device)
  File "/home/kev/ai/src/deep-imagen/imagen.py", line 217, in load
    imagen = load_imagen_from_checkpoint(path)
  File "/home/kev/anaconda3/envs/ai/lib/python3.10/site-packages/imagen_pytorch/utils.py", line 37, in load_imagen_from_checkpoint
    imagen = imagen_klass(**imagen_params).create()
  File "/home/kev/anaconda3/envs/ai/lib/python3.10/site-packages/imagen_pytorch/configs.py", line 125, in create
    imagen = ElucidatedImagen(unets, **decoder_kwargs)
TypeError: ElucidatedImagen.__init__() got an unexpected keyword argument 'video'
```

**Comment by lucidrains** [comment]
@deepglugs :sweat_smile:   https://github.com/lucidrains/imagen-pytorch/commit/9c6ff50c6546c5461b9f0ccf5287a5520a991ce8

**Comment by deepglugs** [comment]
Looks like I need to set sigma_max (for Elucidated) down to something really low to get the images to pop out looking like each other:

![image](https://user-images.githubusercontent.com/70453896/184039035-4c2d16da-a1bf-4364-a6f5-80bba955fa5e.png)
sigma_max=1.0.

I wasn't able to go below 1.0, however.  0.1, 0.5 and 0.75 resulted in black images.  Would be nice to be able to tune sigma_min/max and the number of sample steps inside of the sample function.  You can't adjust these if you are using load_from_checkpoint().  I ended up having to construct a new ElucidatedImagen class, and then manually torch.load the model state dict.

Super cool that we can do this though :)

**Comment by lucidrains** [comment]
@deepglugs here you go! https://github.com/lucidrains/imagen-pytorch/commit/a936ea72e99d62d89d464c266e919deecf4437ed
