### ISSUE TITLE
About extrapolation

### ISSUE THREAD

**Issue by martinriven** [lucidrains/imagen-pytorch#173]
It might be silly, but I notice that in README(text to video), you show that it can extrapolate videos; But I can't find where it is implemented? All I can find is that you shape the sample video longer, but don't know how you extrapolate.

**Comment by lucidrains** [comment]
@martinriven i'm using axial attention across time as was done in Ho's recent work with video ddpm

the type of positional encoding i've adopted is attention bias parameterized by an MLP, and has very good extrapolation properties, evidenced by [SwinV2](https://arxiv.org/abs/2111.09883) and [experiments from independent researchers](https://github.com/lucidrains/x-transformers#dynamic-positional-bias)

**Comment by martinriven** [comment]
thx!! I'm gonna check it out.
