### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by xiaojinzi123** [lucidrains/imagen-pytorch#179]
![image](https://user-images.githubusercontent.com/12975743/184844489-7594003f-fe73-47d5-98d8-17518d901a81.png)

**Comment by emirefek** [comment]
That problem is not related with this repository. You need to learn how to install Pytorch with Nvidia CUDA libraries

**Comment by xiaojinzi123** [comment]
Thank you
