### ISSUE TITLE
p_sample() got an unexpected keyword argument 'self_cond'

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/imagen-pytorch#180]
Error caused by line 2086 in imagen_pytorch.py.

**Comment by lucidrains** [comment]
@xiankgx whoops! https://github.com/lucidrains/imagen-pytorch/commit/1a8292c5339478d4b59907c4b61f0598c5d9d8c6 🙏

**Comment by xiankgx** [comment]
Thank you so much.
