### ISSUE TITLE
How to speed up sampling?

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/imagen-pytorch#181]
Hi @lucidrains , are you aware of any method to speed up sampling after the model is trained?

**Comment by lucidrains** [comment]
@xiankgx i'm only familiar with ddim and not some of the more recent techniques

open to suggestions and discussion on what should be added!

**Comment by lucidrains** [comment]
@xiankgx i'm only familiar with ddim and not some of the more recent techniques

open to suggestions and discussion on what should be added!

**Comment by lucidrains** [comment]
@xiankgx you aren't using elucidated ddpm?

**Comment by xiankgx** [comment]
What the difference between the two versions of Imagen? I have just started to look at image gen again.

**Comment by lucidrains** [comment]
the elucidated version has a new formulation, and brings sampling down to 32-64 steps

**Comment by lucidrains** [comment]
@xiankgx i've removed discrete time gaussian diffusion, so there is no more notion of steps during training

time is sampled from a uniform distribution from 0 to 1 in base imagen, and in elucidated ddpm, from a log normal distribution

**Comment by lucidrains** [comment]
@xiankgx for base imagen, timesteps would be equivalent to the number of sampling timesteps (ddpm version, i haven't added the ddim version yet)
