### ISSUE TITLE
Any concerns with training with mixed precision?

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/imagen-pytorch#183]
Hi, do you foresee any problems with training with 16 bit precision?

**Comment by xiankgx** [comment]
Also, I think it is common to use 1000 time steps. Have you tried with much less say 200?

**Comment by lucidrains** [comment]
yeah, i've heard people train with mixed precision with good results

**Comment by lucidrains** [comment]
200 steps should be fine, though you will always suffer higher FID once you go below 400 timesteps
