### ISSUE TITLE
q, k, v = rearrange_many((q, k, v), 'b n (h d) -> b h n d', h=h)

### ISSUE THREAD

**Issue by zzw-zwzhang** [lucidrains/imagen-pytorch#19]
After this, q: [4, 256, 512] -> [4，8，32，64].

Why is the shape of q not [4，8，256，64]?

[https://github.com/lucidrains/imagen-pytorch/blob/ae26caef19d64816fde51a4a4ccc45078bb70566/imagen_pytorch/imagen_pytorch.py#L402](https://github.com/lucidrains/imagen-pytorch/blob/ae26caef19d64816fde51a4a4ccc45078bb70566/imagen_pytorch/imagen_pytorch.py#L402)

**Comment by lucidrains** [comment]
so the queries in the perceiver is actually a learned set of latents (which attention pools over the sequence), and can be any length
