### ISSUE TITLE
How to retrain unconditional Imagen model

### ISSUE THREAD

**Issue by sharonibejih** [lucidrains/imagen-pytorch#194]
I trained a model that is not conditioned on text, following this description on the README:

```
unet = Unet(
    dim = 32,
    dim_mults = (1, 2, 4, 8),
    num_resnet_blocks = 1,
    layer_attns = (False, False, False, True),
    layer_cross_attns = False
)

# imagen, which contains the unet above

imagen = Imagen(
    condition_on_text = False,  # this must be set to False for unconditional Imagen
    unets = unet,
    image_sizes = 128,
    timesteps = 1000
)

trainer = ImagenTrainer(
    imagen = imagen,
    split_valid_from_train = True, # whether to split the validation dataset from the training
    # imagen_checkpoint_path = "./ckpt.pt"
).cuda()
```
But to retrain, I added the `imagen_checkpoint_path` arg in the `ImagenTrainer`, with the path to my previously trained model. But I get an error message stating that the checkpoint must contain a config. I traced this and discovered it is because I used Imagen and not ImagenConfig, which is understandable. 

So now that I have a model trained with Imagen that is not conditioned on text, is there a way I can load the model and retrain? 

### I have tried the following:
```
# load checkpoint
trainer.load("./ckpt.pt")

dataset = Dataset('./image_data/', image_size = 128)

trainer.add_train_dataset(dataset, batch_size = 16)
```

And that worked, **except that I could not get the loss of each timestep in this new training** because whenever I run:
```
for i in range(20000):

    loss = trainer.train_step(unet_number = 1, max_batch_size = 4)
    print(f'loss: {loss}')`
```
### It gives me the following error:

**RuntimeError: output with shape [128, 1, 1] doesn't match the broadcast shape [1, 128, 1, 1]**

Is there a way to retrain a model with Imagen that is not conditioned with text, and also get the loss values in each timestep?

**Comment by lucidrains** [comment]
Hi Sharon,

Could you send me the full trace of the very last error?

**Comment by lucidrains** [comment]
@sharonibejih could you paste the script you are using for loading the old checkpoint? are you instantiating the trainer and all the unets identically to the first run? haha, this is why it is better to use the config (as it is saved within the checkpoint)

**Comment by lucidrains** [comment]
this runs for me without any issues

```python
from imagen_pytorch import Unet, Imagen, ImagenTrainer
from imagen_pytorch.data import Dataset

# unets for unconditional imagen

unet = Unet(
    dim = 32,
    dim_mults = (1, 2, 4, 8),
    num_resnet_blocks = 1,
    layer_attns = (False, False, False, True),
    layer_cross_attns = False
)

# imagen, which contains the unet above

imagen = Imagen(
    condition_on_text = False,  # this must be set to False for unconditional Imagen
    unets = unet,
    image_sizes = 128,
    timesteps = 1000,
)

trainer = ImagenTrainer(
    imagen,
    fp16 = True,
    split_valid_from_train = True,
    split_valid_fraction = 0.02,
).cuda()

# instantiate your dataloader, which returns the necessary inputs to the DDPM as tuple in the order of images, text embeddings, then text masks. in this case, only images is returned as it is unconditional training

train_ds = Dataset('/path/to/data', image_size = 128)

trainer.add_train_dataset(train_ds, batch_size = 32)

# working training loop

for i in range(1):
    loss = trainer.train_step(unet_number = 1, max_batch_size = 4)
    print(f'loss: {loss}')

trainer.save('./test.pt')

del trainer

# unets for unconditional imagen

unet = Unet(
    dim = 32,
    dim_mults = (1, 2, 4, 8),
    num_resnet_blocks = 1,
    layer_attns = (False, False, False, True),
    layer_cross_attns = False
)

# imagen, which contains the unet above

imagen = Imagen(
    condition_on_text = False,  # this must be set to False for unconditional Imagen
    unets = unet,
    image_sizes = 128,
    timesteps = 1000,
)

trainer = ImagenTrainer(
    imagen,
    fp16 = True,
    split_valid_from_train = True,
    split_valid_fraction = 0.02
)

trainer.add_train_dataset(train_ds, batch_size = 32)

trainer.load('./test.pt')

for i in range(2):
    loss = trainer.train_step(unet_number = 1, max_batch_size = 4)
    print(f'loss: {loss}')
```

**Comment by sharonibejih** [comment]
Thanks, @lucidrains for your support. It was really timely. 

I had done exactly what you did though. 

When I copied this code you shared with me and tried my model on it (ckpt.pt), I ran into the same error. But when I trained a simple model afresh (like you did), and reloaded it for retraining, it worked fine. 

So, am I right to suspect that it is due to version differences? cos I get this line while reloading the model (ckpt.pt):
```
loading saved imagen at version 1.9.6, but current package version is 1.10.1
```

If I choose to forgo the models I have with 1.9.6 and do a new one, do you think 1.10.1 is currently stable so that I don't lose any new models with its version?


Secondly, speaking of using config, as you suggested, can it work on unconditional training? Because the ImagenConfig class for example does not have the boolean ```condition_on_text``` attribute like Imagen.

**Comment by lucidrains** [comment]
@sharonibejih yeah unfortunately if the version numbers increment that isn't the right most digit, you should expect a breaking change

you can try `trainer.load('./model.ckpt', strict = False)` and then continue training and see if it snaps back into place (you should expect to see an initially high loss)

**Comment by lucidrains** [comment]
@sharonibejih or you can just stick with the version of imagen-pytorch with which the model was trained

**Comment by Nodja** [comment]
I've just upgraded from a lower version (1.9.3) to test SPD-Conv and had a similar error, I had to pass `strict=False` like lucid said but also `only_model=True`. For my unet passing `lr=1e-5` to the trainer was also good enough that the loss was initially only a bit higher than usual.

**Comment by sharonibejih** [comment]
Great! I will try these. Thank you, @lucidrains.

**Comment by sharonibejih** [comment]
> I've just upgraded from a lower version (1.9.3) to test SPD-Conv and had a similar error, I had to pass `strict=False` like lucid said but also `only_model=True`. For my unet passing `lr=1e-5` to the trainer was also good enough that the loss was initially only a bit higher than usual.

This is really helpful. Thanks, @Nodja.
