### ISSUE TITLE
Regarding layer_attn and use_linear_attn

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/imagen-pytorch#202]
https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L1295

`transformer_block_klass = TransformerBlock if layer_attn else (LinearAttentionTransformerBlock if use_linear_attn else Identity)`

Is this supposed to mean:

`transformer_block_klass = (LinearAttentionTransformerBlock if use_linear_attn else TransformerBlock) if layer_attn else Identity`

**Comment by lucidrains** [comment]
It is supposed to be like that, so one can fallback to using sparse linear attention if full quadratic attention is too expensive

Your logic would force all layers to use sparse attention, which would be suboptimal

**Comment by lucidrains** [comment]
yea I can fix that logic so one can remove attention

right now use_linear_attn will make it so the removed full quadratic attention becomes sparse linear

**Comment by xiankgx** [comment]
It is ok if this is intentional. Just thought to raise this up.

**Comment by lucidrains** [comment]
Thanks! I'll think of a less confusing design 👍

**Comment by lucidrains** [comment]
@xiankgx do you want to double check this commit? https://github.com/lucidrains/imagen-pytorch/commit/d4c45ab1c8380de71e5dd1044dc4100ef9ac76ce you can now pass in a tuple to `use_linear_attn` ex. `use_linear_attn = (False, True, False, False)`
