### ISSUE TITLE
Can we finetune on a trained model?

### ISSUE THREAD

**Issue by PeterRanieri** [lucidrains/imagen-pytorch#21]
I understand that there is no trained model out in public yet,
however when there is a trained model on LAION dataset;
will we be able to fine-tune on our own specific text-image pair dataset?

**Comment by ProGamerGov** [comment]
There should be no reason you couldn't, provided of course you have the GPU resources to do so.

**Comment by apockill** [comment]
Is there any place we can donate to support the training of a base LAION-trained model?

**Comment by lucidrains** [comment]
@apockill just join the Laion discord community and ask around :)

**Comment by lucidrains** [comment]
> I understand that there is no trained model out in public yet, however when there is a trained model on LAION dataset; will we be able to fine-tune on our own specific text-image pair dataset?

why not? :)

**Comment by kyle-cx** [comment]
> There should be no reason you couldn't, provided of course you have the GPU resources to do so.

if we  fine-tune on our own specific text-image pair dataset when there is a trained model on LAION dataset, How much GPU resources are needed, I have only an NVIDIA GeForce RTX 3060
@ProGamerGov @lucidrains
