### ISSUE TITLE
Relationship with the repo video-diffusion-pytorch

### ISSUE THREAD

**Issue by wenyihong** [lucidrains/imagen-pytorch#210]
Thanks so much for providing the code of image/video diffusion model! 

What is the relationship between this repository and https://github.com/lucidrains/video-diffusion-pytorch? Is the video diffusion model the same as that in video-diffusion-pytorch? Also, which of the two repos will be updated if there are updates about video diffusion model?

**Comment by lucidrains** [comment]
@wenyihong hey no problem! yes, it incorporates the unet design from Jonathan Ho's video diffusion paper, and also makes it compatible for cascading ddpm styled progressive upsampling, text conditioning, dynamic thresholding etc

**Comment by lucidrains** [comment]
@wenyihong and yea, it will incorporate all future improvements in the text to video space. i expect a lot of new findings in the upcoming machine learning conferences in the coming year
