### ISSUE TITLE
Missing attribute in ElucidatedImagen: image_sizes

### ISSUE THREAD

**Issue by brandon-holt** [lucidrains/imagen-pytorch#238]
There seems to be no reference to the image_sizes attribute in the ElucidatedImagen class (imagen_pytorch/elucidated_imagen.py).

From Line 170:
        self.image_sizes = cast_tuple(self.image_sizes)

Maybe should be
        self.image_sizes = cast_tuple(image_sizes)

@lucidrains

**Comment by lucidrains** [comment]
oh oops, this PR broke it my bad https://github.com/lucidrains/imagen-pytorch/pull/230/files

should be fixed!

**Comment by brandon-holt** [comment]
no worries, thanks for the reply!

Great work on this project, really appreciate it.
