### ISSUE TITLE
Colab notebook, also nan issue

### ISSUE THREAD

**Issue by Mimocro** [lucidrains/imagen-pytorch#24]
I just made a simple colab training notebook, it seems to work, but got issues. I think, at this moment, it's no reasons to do full training while the code is not finished yet.
https://colab.research.google.com/drive/1zVFcWU7REDmQXKs5gBNAu7kdPEAgG5wy?usp=sharing

Also, when i played with batch size, (if i implemented it right for training, of course), i noticed that the batch size more than 1 causes a 'nan' losses during training. It can be avoided by torch.nn.utils.clip_grad_norm_ i suppose, or changing optimizer to AdamW. 
One more bug: trainer.sample can sample only once, after that there is a "RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same", can be fixed by reinitialization.

Dataset for only 60 images from LAION just to test
https://drive.google.com/file/d/1hiZvegBcunQAR5NrpXXAxnjVMSa7IN4z/view?usp=sharing

And last thing, with losses about 0.3 generated images still be noise.

**Comment by lucidrains** [comment]
@Mimocro hello! :wave: thanks for trying this out! i've put in a fix for that sampling device related bug https://github.com/lucidrains/imagen-pytorch/commit/b3a0c1bfd89656ff3c5147995bf20ddfa5b96ce9

the `nan` should be expected, as there are self attention blocks in the unet, but i'll definitely work on stabilizing it

**Comment by Mimocro** [comment]
@lucidrains thanks for the answer, im looking forward to it.

**Comment by lucidrains** [comment]
@Mimocro yup no problem, welcome you to retry the sampling to make sure that is bug free :)

also, batch sizes should be at least 32, and you can use the `max_batch_size` keyword on the training forward step to automatically prevent OOM

**Comment by Mimocro** [comment]
@lucidrains i tried, yep, sampling bug was gone. But i think, if we feed 3 tensors like [400000, 3, 256, 256] and do `max_batch_size = 32`, it will not save us from  OOM, isn't? And when i replace   `batch = batches[1].split(' ')[:-1]` to  `batch = batches[i].split(' ')[:-1]`, i get nan with batch size 1. Anyway, ill be waiting, that's great.

**Comment by Mimocro** [comment]
I got it right, we need to feed torch tensor with dimensions [1, 3, 256, 256] as image but set `max_batch_size` when calling trainer? So batches will accumulate to 32 and everything will be ok?

**Comment by lucidrains** [comment]
@Mimocro more like `[32|64, 3, 256, 256]` and then you can set the `max_batch_size` to something lower than 32 to prevent OOM

**Comment by lucidrains** [comment]
basically you are telling the system you don't want the batch size processed to be too large and hit OOM

**Comment by Mimocro** [comment]
@lucidrains  thanks for the explanation.

**Comment by jacobwjs** [comment]
> @lucidrains yeah, it will save you from OOM, that's [gradient accumulation](https://towardsdatascience.com/what-is-gradient-accumulation-in-deep-learning-ec034122cfa)

Really amazing work Phil. Curious, how will this handrolled grad accum play with distributed training and syncing gradients across N devices after a step. And to a further extreme across M nodes. After all, this is the playground for such a model. Any intuitions?

**Comment by jacobwjs** [comment]
> @Mimocro yup no problem, welcome you to retry the sampling to make sure that is bug free :)
> 
> also, batch sizes should be at least 32, and you can use the `max_batch_size` keyword on the training forward step to automatically prevent OOM

How did you come to 32?

**Comment by KyriaAnnwyn** [comment]
> I just made a simple colab training notebook, it seems to work, but got issues. I think, at this moment, it's no reasons to do full training while the code is not finished yet. https://colab.research.google.com/drive/1zVFcWU7REDmQXKs5gBNAu7kdPEAgG5wy?usp=sharing
> 
> Also, when i played with batch size, (if i implemented it right for training, of course), i noticed that the batch size more than 1 causes a 'nan' losses during training. It can be avoided by torch.nn.utils.clip_grad_norm_ i suppose, or changing optimizer to AdamW. One more bug: trainer.sample can sample only once, after that there is a "RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same", can be fixed by reinitialization.
> 
> Dataset for only 60 images from LAION just to test https://drive.google.com/file/d/1hiZvegBcunQAR5NrpXXAxnjVMSa7IN4z/view?usp=sharing
> 
> And last thing, with losses about 0.3 generated images still be noise.

In the collab notebook only the first batch is of the defined size, second ans all other batches are batch_size - 1. But as the dataset consists of 60 samples this has no effect, first batch is 32, second 28. If dataset size is 64< you get 32, 31,1, batches.

**Comment by KyriaAnnwyn** [comment]
> @lucidrains i tried, yep, sampling bug was gone. But i think, if we feed 3 tensors like [400000, 3, 256, 256] and do `max_batch_size = 32`, it will not save us from OOM, isn't? And when i replace `batch = batches[1].split(' ')[:-1]` to `batch = batches[i].split(' ')[:-1]`, i get nan with batch size 1. Anyway, ill be waiting, that's great.

Got not nan loss for 77 epochs with 32/31/1 batches. But when corrected it I get nan loss at the first epoch :(

**Comment by Mimocro** [comment]
> In the collab notebook only the first batch is of the defined size, second ans all other batches are batch_size - 1. But as the dataset consists of 60 samples this has no effect, first batch is 32, second 28. If dataset size is 64< you get 32, 31,1, batches.

Sorry, im stupid a bit.. Anyway it's fixed in colab just now, but im still getting nan. 

I tried to make some... things due to avoid, or, better to say, dodge the nan issue, And it's getting weird more and more...

**Comment by KyriaAnnwyn** [comment]
> > In the collab notebook only the first batch is of the defined size, second ans all other batches are batch_size - 1. But as the dataset consists of 60 samples this has no effect, first batch is 32, second 28. If dataset size is 64< you get 32, 31,1, batches.
> 
> Sorry, im stupid a bit.. Anyway it's fixed in colab just now, but im still getting nan.
> 
> I tried to make some... things due to avoid, or, better to say, dodge the nan issue, And it's getting weird more and more...

Also trying to get rid of nans.

**Comment by Mimocro** [comment]
@KyriaAnnwyn check last version of my colab, i think main problem is a trainer class, loss < 1 after one epoch on small dataset are really suspicious and i figured out what training with 
`    loss = imagen(images, text_embeds = text_embeds, text_masks = text_masks, unet_number = i)`
`    loss.backward()`
dont returns nan losses, and also with that, using torch.nn.utils.clip_grad_norm_ are easier than append that to 454 line to traier.py (i didnt tried this yet).
Also losses after first epochs about 9, not 1, and it looks more normally.

**Comment by KyriaAnnwyn** [comment]
> @KyriaAnnwyn check last version of my colab, i think main problem is a trainer class, loss < 1 after one epoch on small dataset are really suspicious and i figured out what training with ` loss = imagen(images, text_embeds = text_embeds, text_masks = text_masks, unet_number = i)` ` loss.backward()` dont returns nan losses, and also, with that, using torch.nn.utils.clip_grad_norm_ are easier than append that to 454 line to traier.py (i didnt tried this yet). Also losses after first epochs are about 9, not 1, and it looks more normally.

The input images should be float in the fange [-1,1].
I changed loading function as follows:
```
def get_images_tensor(files):
    img_arr = []
    transforms = torch.nn.Sequential(
        T.Resize([256, 256]),
        T.ConvertImageDtype(torch.float)
    )
    for i in files:
       img_arr.append((transforms(torchvision.io.read_image(i, torchvision.io.ImageReadMode.RGB)) * 2 - 1).unsqueeze(0))

    return torch.cat((img_arr), dim=0)
```

The losses becane good ^)

**Comment by Mimocro** [comment]
Oh, so it's my fault, im sorry.

**Comment by lucidrains** [comment]
@KyriaAnnwyn ohh actually, that should not be necessary, since i do auto-normalization both during training, and inverse normalization on sampling https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L1230

**Comment by Mimocro** [comment]
@lucidrains its a fix for my colab, i forget to normalize image before feeding it to trainer and auto-normalization seems do not really make images normalized. Also i training a model on dataset with 122k images, and i realized what ema fix from https://github.com/lucidrains/imagen-pytorch/issues/25 not working, still need to `use_ema = False` or sampling results constain only noise.

**Comment by KyriaAnnwyn** [comment]
> @KyriaAnnwyn ohh actually, that should not be necessary, since i do auto-normalization both during training, and inverse normalization on sampling https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L1230

The images that produced nans were uint8 from 0 to 255. And normalization was for [0,1] images. Maybe *2 - 1 was really not necessary

**Comment by lucidrains** [comment]
@KyriaAnnwyn ohhh, yea, images you passed in must range from 0 to 1

**Comment by lucidrains** [comment]
@KyriaAnnwyn ohh, yea, images you pass in must be normalized from 0 to 1 (which torchvision should take care of if you are using the `transforms.ToTensor()` method)

**Comment by lucidrains** [comment]
> @lucidrains its a fix for my colab, i forget to normalize image before feeding it to trainer and auto-normalization seems do not really make images normalized. Also when i train a model on dataset with 122k images, i realized what ema fix from #25 not working, still need to `use_ema = False` or sampling results only noise.

autonormalize isn't working?

**Comment by Mimocro** [comment]
> autonormalize isn't working?
I mean, images does not normalize into [0,1] from [0,255]

**Comment by lucidrains** [comment]
@Mimocro ohh i see why

```python
def get_images_tensor(files):
    img_arr = []
    transforms = torch.nn.Sequential(
        T.Resize([256, 256]),
        T.ConvertImageDtype(torch.float)
    )
    for i in files:
       img_arr.append((transforms(torchvision.io.read_image(i, torchvision.io.ImageReadMode.RGB)) * 2 - 1).unsqueeze(0))
    img_embeds = torch.cat((img_arr), dim=0).to('cuda')
    return img_embeds
```

you can actually just use https://pytorch.org/vision/main/generated/torchvision.transforms.ToTensor.html

**Comment by lucidrains** [comment]
yea, normalization is confusing, i'll definitely automate this bit away

**Comment by MattJeanes** [comment]
I've taken your colab notebook cleaned it up a bit and added support for png and jpeg files (jpg already there), added separate checkpoint save files and couple other little bits.

I've also set it up to work in a VSCode dev container so you can run this locally if you have the hardware as long as you've got WSL2, at least Windows 10 21H2 (for GPU passthrough) and Docker Desktop installed.

If anyone is interested, here it is: https://github.com/MattJeanes/imagen-notebook

**Comment by iammatthias** [comment]
@MattJeanes not sure about Intel Macs (guess it would depend on Nvidia vs ARM gpu), but this does not work on Apple Silicon systems. 

If Imagen-Pytorch can be modified to use CUDA or MPS, then it should work without issue.

https://pytorch.org/docs/master/notes/mps.html

```python
AssertionError                            Traceback (most recent call last)
/Users/iammatthias/ml/imagen-notebook/imagen_train.ipynb Cell 2' in <cell line: 102>()
     85 unet1 = Unet(
     86     dim = 32,
     87     cond_dim = 512,
   (...)
     90     layer_attns = (False, True, True, True),
     91 )
     93 unet2 = Unet(
     94     dim = 32,
     95     cond_dim = 512,
   (...)
     99     layer_cross_attns = (False, False, False, True)
    100 )
--> 102 imagen = Imagen(
    103     unets = (unet1, unet2),
    104     image_sizes = (64, 256),
    105     beta_schedules = ('cosine', 'linear'),
    106     timesteps = timesteps,
    107     cond_drop_prob = 0.5
    108 ).cuda()
    110 trainer = ImagenTrainer(imagen, use_ema = use_ema)
    112 #feed images into imagen, training each unet in the cascade
    113 #try to load last ckpt
...
    212 if _cudart is None:
    213     raise AssertionError(
    214         "libcudart functions unavailable. It looks like you have a broken build?")

AssertionError: Torch not compiled with CUDA enabled
```

**Comment by MattJeanes** [comment]
@iammatthias CUDA is already required for this, I don't think it will work on Apple Silicon devices unless they have a Nvidia GPU installed (I'm not sure if that's even possible) as CUDA is Nvidia proprietary tech. I don't know much about MPS but my understanding is that is also Nvidia tech.
