### ISSUE TITLE
Why there is only one head for key and value?

### ISSUE THREAD

**Issue by XavierXiao** [lucidrains/imagen-pytorch#255]
In the Attention block, the [projection to k and v](https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L487) is defined as 
```self.to_kv = nn.Linear(dim, dim_head * 2, bias = False)```

So the parameters are shared across heads? I think this is not the case in common multi-head attention. Is there any references?

**Comment by lucidrains** [comment]
@XavierXiao it is from https://arxiv.org/abs/1911.02150 and adopted for PaLM https://arxiv.org/abs/2204.02311
