### ISSUE TITLE
Large scale training

### ISSUE THREAD

**Issue by mrkulk** [lucidrains/imagen-pytorch#259]
Hi @lucidrains 

Are you or anyone scaling this up on LAOIN + other datasets?

**Comment by TheFusion21** [comment]
#207

**Comment by lucidrains** [comment]
@mrkulk why not work with Stability.ai? round up some of your best machine learning engineers and start up a collaboration.

**Comment by lucidrains** [comment]
@mrkulk try to bring something to the table, perhaps some competent machine learning engineers from your organization

**Comment by lucidrains** [comment]
@mrkulk to answer your question, no, I am personally not doing any training at the moment

I am currently working on [Phenaki](https://github.com/lucidrains/phenaki-pytorch), [AudioLM](https://github.com/lucidrains/audiolm-pytorch), and will get around to Imagen-video + Imagen-video-dreambooth here near end of month
