### ISSUE TITLE
Cpu only? Cpu and Gpu, or Gpu and Cpu?

### ISSUE THREAD

**Issue by Shikamaru5** [lucidrains/imagen-pytorch#269]
Is there a way to make this cpu only, either that or make it so that it'll use the GPU until it runs out of memory and then use the cpu, or vice versa?

My computer can run diffusion models with my cpu but I have a little less than what the program needs to run on the gpu. I'm guessing that it'd run fairly quickly if it could utilize the entirety of the gpu first and then switch to the cpu but I haven't found a good solution for that yet. Looking at the code it seems that Torch is pretty integrated into how this one operates so I don't want to go deleting a bunch of stuff that'll make it not work at all.

Anyway, I appreciate you taking the time to read this, and I hope even if you don't know the answer, you may know where to point me in the right direction.

**Comment by TheFusion21** [comment]
@Shikamaru5 Take a look at the accelerate feature and it's support for DeepSpeed with which you are able to offload some stuff to the CPU lightening the Memory footprint on the GPU

**Comment by Shikamaru5** [comment]
@TheFusion21 Well I was pretty excited about your suggestion, but alas, it seems that triton is out of date and isn't supported on Windows, along with deepspeed also not being supported on windows because of it, after trying to manually install all of the specific libraries I haven't been able to make it work. Thank you for the suggestion though, it seemed like I was so close with this one!

**Comment by Shikamaru5** [comment]
I did however, manage to free up a little bit of memory using try, except. It went from requiring 64 mib to 20 mib, might not be a huge deal but every little bit counts, I think at least.

I simply said in the train file that anything using cuda should try to use it and if an except RuntimeError occurs func.to('cpu').
Hopefully I can come up with an even better way to do that, but for now it gives me a glimmer of hope.
