### ISSUE TITLE
unet.self_cond error

### ISSUE THREAD

**Issue by Darius-H** [lucidrains/imagen-pytorch#272]
https://github.com/lucidrains/imagen-pytorch/blob/bdfc2f7865eb120b08ed7f156f52c3a64040c613/imagen_pytorch/imagen_pytorch.py#L2405
I think you lost the .self_cond after unet in the end of this row

**Comment by lucidrains** [comment]
thanks! https://github.com/lucidrains/imagen-pytorch/commit/dda987fa741cdef5282d5fba749a8091b9921f26
