### ISSUE TITLE
broken 1.16

### ISSUE THREAD

**Issue by TheFusion21** [lucidrains/imagen-pytorch#273]
Im not sure but it seems it broke with the release of 1.16
gettings very blue or red samples and no good results

**Comment by lucidrains** [comment]
oh was this fixed? btw, there's new research with a new objective that is supposed to be less prone to color shifting (pred_v)

**Comment by TheFusion21** [comment]
was my mistake disabled EMA and wierd stuff happened

**Comment by lucidrains** [comment]
oh yea, EMA is essential! ok, false alarm haha
