### ISSUE TITLE
No module named 'imagen_pytorch.t5'; 'imagen_pytorch' is not a package

### ISSUE THREAD

**Issue by 2kinto** [lucidrains/imagen-pytorch#279]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/16780209/204768349-5be6edf3-c8e2-42bf-b0b1-e6a2e2526c34.png">

I ran the pip install imagen-pytorch command first and used setup.py. I also tried changing the version of pytorch and cuda and python but nothing worked. Does anyone know how to fix it?

**Comment by 2kinto** [comment]
Fixed

**Comment by ku-haeeun** [comment]
hello, I'm having the same problem, sorry but could you tell me how to fix it?? PLEASE
