### ISSUE TITLE
CLI Command Infinite Download Issue

### ISSUE THREAD

**Issue by AngryChihuahua04** [lucidrains/imagen-pytorch#285]
Hi all!

I am very new to ML, but this applications interests me very much. I was trying to get my feet wet with it by using the CLI commands listed in the readme. However, when I run `imagen train`, it starts to download the 2.7GB file. Once it finishes, it starts to download 2.7GB again. 

Has anybody else had this issue or know how to fix it?

**Comment by TheFusion21** [comment]
The default dataset is big and split into a few parts 127 2.7GB files to be exact

**Comment by AngryChihuahua04** [comment]
Oh ok. Thanks for the clarification!
