### ISSUE TITLE
transformers T5Large version

### ISSUE THREAD

**Issue by deepglugs** [lucidrains/imagen-pytorch#33]
I am seeing a warning about "Some weights of the model checkpoint at t5-large were not used when initializing T5EncoderModel".  I am using the latest transfomers version in pypi (4.19.2)... can this be ignored?

**Comment by lucidrains** [comment]
@deepglugs yup, it is because we are only using the encoder (not the decoder)

**Comment by Infinitay** [comment]
Jumping on to this, would you mind sharing the proper way to load and use T5 with the existing imagen-pytorch example?
