### ISSUE TITLE
Inpainting with Videos (UNET3D)

### ISSUE THREAD

**Issue by MrBirrd** [lucidrains/imagen-pytorch#338]
Is it possible to inpaint in videos? I tried to pass it just the inpaint images but let them be a video batch the same size as during training, however then the assertion also reminds me that

`'video_frames must be passed in on sample time if training on video'
AssertionError: video_frames must be passed in on sample time if training on video`

**Comment by lucidrains** [comment]
@MrBirrd ah yea, that was on my todo

i hacked in support for [single mask across frame video inpainting](https://github.com/lucidrains/imagen-pytorch#inpainting), but will eventually support an inpaint mask with a frame dimension greater than 1

i'll also have to rename the `inpaint_images` to be modality agnostic at some point

**Comment by lucidrains** [comment]
@MrBirrd should be all good now https://github.com/lucidrains/imagen-pytorch/commit/8be7a30760a37b090e85783ff4442db8b7582500
