### ISSUE TITLE
Triton Python 3.10 and up

### ISSUE THREAD

**Issue by Jammers33** [lucidrains/imagen-pytorch#366]
In your setup.py you have a call to triton, which seems to be no longer supported for python 3.10  higher, as there tends to be a version error, "ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton" Perhaps you could either put a git pull directly in the setup.py or update the script, requesting permission to fork for alterations before doing so, as installing it directly doesn't seem to quash the issue due to the requirements in the setup.py

**Comment by lucidrains** [comment]
@Jammers33 i don't think it was being used, so i removed it https://github.com/lucidrains/imagen-pytorch/commit/4a34864cd25de7a52fe41a924a91be45e86bc7d8
