### ISSUE TITLE
learned variance

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/imagen-pytorch#37]
does anyone have an opinion on whether learned variance was used in Imagen? it would greatly simplify the project if i can just remove it

**Comment by samedii** [comment]
The tips in this article improved results a lot for me in another project. Different parameterization, adding a lot of noise, and better sampling method
https://arxiv.org/abs/2206.00364

No learned variance.

**Comment by lucidrains** [comment]
@samedii thanks Richard! Tero Karras is legendary :)

**Comment by lucidrains** [comment]
@samedii :100: 100: you are getting a shout out if i end up using any of your code examples :)

**Comment by lucidrains** [comment]
ok, one more researcher tells me learned variance doesn't work for him/her and i'm removing it

**Comment by lucidrains** [comment]
ok, one more researcher tells me learned variance doesn't work for him/her and i'm removing it and not looking back
