### ISSUE TITLE
Saving Images

### ISSUE THREAD

**Issue by 3DTOPO** [lucidrains/imagen-pytorch#4]
I'm not certain I am saving the tensor to images correctly.

All I seem to get is noise - albeit it does have some structure to it. I tried 10,000 time steps and still just noise.

```
from torchvision.utils import save_image
img1 = images[0]  #torch.Size([3, 256, 256])
save_image(img1, 'img1.png’)
```

I’ve tried other ways such as:

```
from torchvision import transforms
im = transforms.ToPILImage()(images[0]).convert("RGB”)
im.save('img1.png’)
```

But I get results like this regardless:

![img1 copy](https://user-images.githubusercontent.com/352383/170374375-4ce5445b-1d13-4de5-9fc6-142c6f4bfdb1.png)

**Comment by lucidrains** [comment]
@3DTOPO basically, if you see a `(wip)` in any of my repositories at the top, it is not ready yet

**Comment by 3DTOPO** [comment]
Thanks.

I just assumed it worked since there is an example.

**Comment by lucidrains** [comment]
ohh, the examples is for deep learning practitioners who want to train it (off Laion dataset or their own)

**Comment by lucidrains** [comment]
ohh the example is for training, and there are no publicly available trained model yet

**Comment by CrazyBoyM** [comment]
Is there  any publicly available trained model, i would like to use it to be a web, thanks!

**Comment by lukestanley** [comment]
Not of this.
