### ISSUE TITLE
how to save the image

### ISSUE THREAD

**Issue by BlueCat7** [lucidrains/imagen-pytorch#41]
Dear Author,
    Thanks for your amazing work. I have a question about how to save as a image.  I find the output is between 0 to 1, so I use the below code to save as a image. Looking forward your answer, thanks.

```
images = imagen.sample(texts = [
    'A woman cutting a large white sheet cake.',
    'A woman wearing a hair net cutting a large sheet cake.',
    'A woman wearing a net on her head cutting a cake.'
], cond_scale = 2.)

num_imgs = len(images)
for i in range(num_imgs):
    gen_img = images[i].permute(1,2,0)
    cv2.imwrite('%d.jpg'%i, np.uint8(gen_img.cpu().numpy() * 255))
```

**Comment by BlueCat7** [comment]
![0](https://user-images.githubusercontent.com/25917154/173052089-d622b858-7eef-4eb9-bb35-22fb7163076f.jpg)

**Comment by thedarkzeno** [comment]
I have also trained it for a long time and could only get results that looked like abstract paint, some actually looked like a landscape, but didn't match the prompt at all. Was anyone successful at training with this repo?

**Comment by xXchrizzoXx** [comment]
Dear BlueCat7, 
could you give me a few tips on where to start to train models and save images? I'm very new to all of this...

**Comment by lucidrains** [comment]
@BlueCat7 try https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L1441 `return_pil_images = True`, then you can just call the `save` method directly off the pillow Image instance

**Comment by BlueCat7** [comment]
> @BlueCat7 try https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L1441 `return_pil_images = True`, then you can just call the `save` method directly off the pillow Image instance

Thanks a lot, I will try it.

**Comment by BlueCat7** [comment]
> Dear BlueCat7, could you give me a few tips on where to start to train models and save images? I'm very new to all of this...

Hi, you can reference the Usage in https://github.com/lucidrains/imagen-pytorch#usage, you just simply add a dataloader to produce the image and text pairs, and then run in one gpu. Secondly, you can transfer to multi gpus by DDP.

**Comment by BlueCat7** [comment]
> Dear BlueCat7, could you give me a few tips on where to start to train models and save images? I'm very new to all of this...

Hi, you can reference the Usage in https://github.com/lucidrains/imagen-pytorch#usage, you just simply add a dataloader to produce the image and text pairs, and then run in one gpu. Secondly, you can transfer to multi gpus by DDP.

**Comment by BlueCat7** [comment]
> Dear BlueCat7, 
> 
> could you give me a few tips on where to start to train models and save images? I'm very new to all of this...


Hi, you can reference the Usage in https://github.com/lucidrains/imagen-pytorch#usage, you just simply add a dataloader to produce the image and text pairs, and then run in one gpu. Secondly, you can transfer to multi gpus by DDP.
