### ISSUE TITLE
why perceiver attention?

### ISSUE THREAD

**Issue by GallagherCommaJack** [lucidrains/imagen-pytorch#42]
it seems like the imagen paper doesn't make any references to Perceiver IO - why do you think that's what their "attention pool" mechanism was referring to vs eg a 1d version of something like [AttentionPool2D in CLIP](https://github.com/openai/CLIP/blob/main/clip/model.py#L58)?

**Comment by lucidrains** [comment]
@GallagherCommaJack i think deepmind has investigated and optimized cross attention (perceiver) to its fullest potential than any other team

**Comment by lucidrains** [comment]
@GallagherCommaJack but yea, i can always offer the other weaker version of attention pooling

**Comment by GallagherCommaJack** [comment]
ah that makes sense - the only reason to offer the weaker version is basically pedagogical IMO, since it's much simpler so it's a lot easier to understand what's going on, but not obviously even that much faster since the attention pooling operations should be a tiny fraction of overall compute.

**Comment by lucidrains** [comment]
@GallagherCommaJack yea, i'm not too concerned with the attention portions for any project these days, as i know the landscape better than anyone and have fuller confidence over my abilities

ddpms on the other hand, we need to carefully make sure not to miss any details (which is why i spent a lot of time trying to get the continuous time version working)

**Comment by GallagherCommaJack** [comment]
oh really? I normally find continuous time DDPMs easier to implement.

What was tricky with this one?

**Comment by lucidrains** [comment]
@GallagherCommaJack i'm just not as well read on ddpms as you or Katherine, still catching up :)

**Comment by GallagherCommaJack** [comment]
I think that's right, though I don't normally use log-snr parametrization so not 100% sure.
Normally I just use fourier features of the timestep like in [katherine's cc12m model](https://github.com/crowsonkb/v-diffusion-pytorch/blob/master/diffusion/models/cc12m_1.py#L115)

**Comment by GallagherCommaJack** [comment]
the reasoning being that it's a whole lot simpler than anything else and I haven't found different timestep conditioning setups to produce meaningful differences in model performance, including some surprisingly wacky methods

**Comment by lucidrains** [comment]
@GallagherCommaJack good to know! thank you for sharing that!
