### ISSUE TITLE
Pretrained imagen-pytorch

### ISSUE THREAD

**Issue by davidoort** [lucidrains/imagen-pytorch#47]
Hi! Thanks for creating this project!

I was wondering if there's a pretrained version of this architecture so that I can readily use it for generation without having to worry about finding a dataset and the compute to train the whole thing.

Thank you!
David

**Comment by lucidrains** [comment]
@davidoort my recommendation is to get involved with the Laion community. they have the necessary data and compute, but the bottleneck is people who know how to train neural nets
