### ISSUE TITLE
Possible Breaking Bug

### ISSUE THREAD

**Issue by christyjestin** [lucidrains/imagen-pytorch#48]
https://github.com/lucidrains/imagen-pytorch/blob/bfe761b52c93f53c1a961c0912bed3b33042382c/imagen_pytorch/imagen_pytorch.py#L1575

Think this should be `image` instead of `images` since this is the variable name used elsewhere within this code block. The unnamed variable error went away when I changed the variable to `image`. Although I do think conceptually all instances of `image` (in this code block) should be replaced with `images` instead.

**Comment by lucidrains** [comment]
@christyjestin Hi Christy, thank you for this! https://github.com/lucidrains/imagen-pytorch/commit/4edfa8ef1dd195f3ba82b460838b2da9852ef3fd
