### ISSUE TITLE
feat: Colab Notebook

### ISSUE THREAD

**Issue by sammcj** [lucidrains/imagen-pytorch#5]
It'd be really neat if there was a (free) Google Colab notebook setup for this - https://colab.research.google.com

**Comment by Wheest** [comment]
Right now there is not a set of pretrained models available, and training would require a lot of resources.

A starting point based on the README might be something [like this](https://colab.research.google.com/drive/1RPJaGnADwROUbZ0MCMGCUjpWSGo7vpEU?usp=sharing), but the community will need to provide pretrained models first before a Colab is useful.  Perhaps a PR to add a clean training pipeline with data download would allow a charitable person to provide the compute for this.

**Comment by lucidrains** [comment]
@sammcj yea, recommend not being a bystander and join the Laion community to contribute. it takes a village to get an open sourced model out there
