### ISSUE TITLE
Training with coco dataset resulted in noise:

### ISSUE THREAD

**Issue by prashantkandel12** [lucidrains/imagen-pytorch#56]
I followed [colab notebook](https://github.com/lucidrains/imagen-pytorch/issues/24) to train the model using[ MS-COCO 2014 dataset.](https://cocodataset.org/#download) It resulted  noise. I first trained it for 2 epochs for each Unets as in the sample. It resulted  noise. Then I trained it for 15 epochs for each Unets the result was worse noise output.

**Result after 2 epochs when prompted for house:**
![house before](https://user-images.githubusercontent.com/30668506/173496481-e8ad5f47-8eb7-4b6f-8ff0-9da606491c8b.png)

**Result after 15 epochs when prompted for house:**
![noiseeee](https://user-images.githubusercontent.com/30668506/173496560-36edba92-a725-46dd-b841-03d1bd3dd6bb.png)

Trained on windows PC, RTX 2080 Ti

**Comment by prashantkandel12** [comment]
changed the coco dataset a bit and trainig again for 5 epochs and result is pretty interesting.
prompt: cats and dog
![image](https://user-images.githubusercontent.com/30668506/173507584-a13e085a-cee0-4a86-976e-1835cb5a2e77.png)

**Comment by Mattie** [comment]
How'd you need to change the dataset to make that progress? (Just curious!)

**Comment by lucidrains** [comment]
please join Laion https://discord.com/invite/xBPBXfcFHd

**Comment by prashantkandel12** [comment]
At first used a text file with 5 description for an image...I changed it to same image 5 times and 1 description per text file.
