### ISSUE TITLE
Poor sampling quality in upscaler Unets

### ISSUE THREAD

**Issue by marunine** [lucidrains/imagen-pytorch#58]
I've seen good quality results with the upscaling Unets in your DALLE2 repo but have been having trouble getting similar ones with the Imagen ones over the same training period.

After reviewing the code and the Imagen paper I wonder if this is the problem:
https://github.com/lucidrains/imagen-pytorch/blob/6a04c908f65e39af55263ce3dcacca943b90fc5a/imagen_pytorch/imagen_pytorch.py#L1584

https://github.com/lucidrains/imagen-pytorch/blob/6a04c908f65e39af55263ce3dcacca943b90fc5a/imagen_pytorch/imagen_pytorch.py#L205

I think that this should be `(1.0 - lowres_sample_noise_level)`? I see that you do your augmentation by sampling at a specific timestep based on the overall number of timesteps, but the default of `0.2` would sample at time `200` - which is actually closer to `0.8` augmentation if you were using a linear scale.

As a workaround I am trying to pass `0.8` into my sample function but I'm not sure this is enough to fully address the issue. Maybe it just takes longer to train since the training operates on a full aug level of `1.0` to `0.0` like the paper does, but I'll keep the unet training for now.

**Comment by marunine** [comment]
Actually, since `q_sample` takes `x_start` and _adds_ `noise` then maybe the original code is correct. Not sure what's causing the issue then.

**Comment by lucidrains** [comment]
hmm, I wonder if we could add the gaussian blur augmentation on top, with similar conditioning based on selected blur sigma

though the Imagen paper did tout this technique, so I am unsure why that would be needed

**Comment by lucidrains** [comment]
yea try training for longer, and if it still doesn't perform well, I can build a blur version, using randomly selected sigma for condition (fixed to some value at inference as proposed in paper)

**Comment by lucidrains** [comment]
maybe we can even try stacking the augmentations, as Tero Karras did in his elucidating paper

**Comment by ken012git** [comment]
I also had the same problem and also look into this.

The sampling images from the first level Unet (64x64 or 128x128) look pretty good, but the second level Unet (256x256) could not produce good quality images even training for many days.

I had tried the noise level for augmentation in training and sampling but the quality is not improved. I also tried `use_linear_attn` and adjusting  `p2_loss_weight_gamma` but they do not help either.

**Comment by lucidrains** [comment]
@deepglugs have you had any success with the upscaler? https://github.com/lucidrains/imagen-pytorch/issues/50#issuecomment-1154693357

**Comment by marunine** [comment]
In the paper's pseudocode they do:
```python
def train_step(
  x_lr: jnp.ndarray, x_hr: jnp.ndarray):

  # Add augmentation to the low-resolution image.
  aug_level = jnp.random.uniform(0.0, 1.0)
  x_lr = apply_aug(x_lr, aug_level)

  # Diffusion forward process.
  t = jnp.random.uniform(0.0, 1.0)
  z_t = forward_process(x_hr, t)

  Optimize loss(x_hr, nn(z_t, x_lr, t, aug_level))
```

So I guess two things that may differ here is:
1. Loss calculation - predicing `x_start` directly, ie. the x_hr image?
2. aug_level is uniform across the entire batch rather than random per sample

**Comment by lucidrains** [comment]
@marunine yup, we can definitely try both of those

1. i don't see any mention in the paper that the super resoluting unets needing to have `x_start` prediction, but i can add it

2.  good find! let me go add it now actually

3. i also have some ideas about strengthening the lowres aug level noise conditioning

5.

**Comment by Netruk44** [comment]
My biggest improvement in the upscaler was achieved by changing the default unet2 `dim = 32` to `128` \(inspired by [Friends don’t let friends train small diffusion models](https://nonint.com/2022/05/04/friends-dont-let-friends-train-small-diffusion-models/)\). Training time is much slower and GPU memory usage is much higher, but the upscaler output looks a lot better for me now.

**Comment by lucidrains** [comment]
@Netruk44 that is a great article ❤️

**Comment by marunine** [comment]
For reference, I was training with 128 dim unets for both the Imagen model and DALLE2 model following the advice of that article.

If you have good results then maybe just more training time is needed compared to DALLE2 because of the noise instead of the blur.

I'll keep it going for now while I continue reviewing the paper and the code at least.

**Comment by lucidrains** [comment]
@marunine ok cool, i added the single batch element augmentation noise level https://github.com/lucidrains/imagen-pytorch/commit/cbc1d062f80f7713000b7ecf47e5a6ede8186e97 and i'll finish off the `x_start` prediction objective later tonight + my own ideas for 3

worse comes to worse, we can always pull in the blur augmentation from DALL-E2

**Comment by lucidrains** [comment]
@marunine ok, you can try setting `pred_objectives = ('noise', 'x_start')` and see if that helps! https://github.com/lucidrains/imagen-pytorch/commit/73fc1d1d1ae3debd24236a787af534e2ebe838c7#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R1336

**Comment by lucidrains** [comment]
@marunine ok, and finally, the "improved" low res conditioning https://github.com/lucidrains/imagen-pytorch/commit/54071f090916f98c599b7eb34b40961964d377db in 0.3.0

**Comment by marunine** [comment]
Great! I'll give it a try and let you know how it goes.

**Comment by deepglugs** [comment]
> @deepglugs have you had any success with the upscaler? [#50 (comment)](https://github.com/lucidrains/imagen-pytorch/issues/50#issuecomment-1154693357) pinging @Netruk44 too

With the current default upscaler, I can produce okay 128px and 256px samples.  My progress seems to have leveled out overall with the default unet dim values.  I'm trying unet1 dim at 64 now.

![blue_dress](https://user-images.githubusercontent.com/70453896/173740713-27cb451f-85d4-4070-8f1d-6ffdd609f387.png)

**Comment by marunine** [comment]
It's improving now, but training just takes longer (time wise, not step wise) due to the introduction of the attention in the upscalers. I should have a more clear update in the next day or two.

Though somewhat related, I guess the current model isn't make use of the efficient Unet architecture proposed in the paper that does the Conv before the resnet/self attention for the DBlock. Your UBlock does look like it's already matching what the paper does in terms of ordering, but I guess that's not the usual direction they talk about for traditional Unet architecture. Does that come from another paper?

**Comment by lucidrains** [comment]
> It's improving now, but training just takes longer (time wise, not step wise) due to the introduction of the attention in the upscalers. I should have a more clear update in the next day or two.
> 
> Though somewhat related, I guess the current model isn't making use of the efficient Unet architecture proposed in the paper that does the Conv before the resnet/self attention for the DBlock. Your UBlock does look like it's already matching what the paper does in terms of ordering, but I guess that's not the usual direction they talk about for traditional Unet architecture. Does that come from another paper?

thank you thank you! :pray:

**Comment by lucidrains** [comment]
@marunine yup, i'll revisit the memory efficient unet architecture, have to admit, i only looked at the diagrams and roughly hacked it out haha

**Comment by lucidrains** [comment]
@marunine ohh yes, #2 may be an important detail, should be the default in 0.4.1! :pray: 

i'll also get the hyperparameter flag for toggling between base / efficient unet designs by evening! as for #1, my bias is that more attention should never really hurt the system, if done correctly. but it is probably a good idea to make it configurable

**Comment by lucidrains** [comment]
@marunine did the x0 prediction objective do anything at all? i may just remove that if it turned out to be unnecessary

**Comment by marunine** [comment]
I was seeing it improve at least before the downscaling changes, so I don't think it hurts, but it might be worth going back to the regular objective if you feel that it isn't fully fleshed out.

**Comment by lucidrains** [comment]
@marunine ok, we'll keep it around!

**Comment by ken012git** [comment]
> @marunine @ken012git how does it look? any better?

I tried v0.3.0 but it seems still suffering from the tinting problem in the 512x512 images' background for training around 30k steps. My training images are all in white background but the background of 512x512 sampling images are either light blue or grey, and the content is still noisy. Let's see if the quality for 512x512 will be improved for more training steps.

The first Unet still produces good 128x128 images for training around 100k steps.

In order to accelerate training a little bit, I tried unconditional image generation with smaller Unets in both resolution with 2 resnet blocks in each Unet block. Below is my configuration:
```
    unet1 = Unet(
        dim = 32,
        cond_dim = 512,
        dim_mults = (1, 2, 4, 8),
        num_resnet_blocks = (2, 2, 2, 2),    # small
        layer_attns = (False, False, False, True),
        layer_cross_attns = (False, False, False, True),
        use_linear_attn = False,
    )
    unet2 = Unet(
        dim = 32,
        cond_dim = 512,
        dim_mults = (1, 2, 4, 8),
        num_resnet_blocks = (2, 2, 2, 2),    # small
        lowres_cond = True,
        layer_attns = (False, False, False, True),
        layer_cross_attns = (False, False, False, True),
        use_linear_attn = False,
    )
    imagen = Imagen(
        condition_on_text = False,   # this must be set to False for unconditional Imagen
        unets = (unet1, unet2),
        image_sizes = (128, 256),
        beta_schedules = ('cosine', 'cosine'),
        timesteps = 1000,
        auto_normalize_img = False,
        continuous_times = True,
        p2_loss_weight_gamma = 1,
    )
```

**Comment by marunine** [comment]
You will probably need to retrain the first Unet a bit because of the change in downsample order, or at least wait until there's an option to flip it.

**Comment by lucidrains** [comment]
@marunine it is done! https://github.com/lucidrains/imagen-pytorch/commit/3cd4fd7519b09af6171d4dbebc32d6f307539019

**Comment by ken012git** [comment]
Thanks!

I trained my both Unet with v0.3.0. I will trained both Unet with v0.4.x later.

However, please help me review if unet configuration. The problem may also in my configuration...

**Comment by marunine** [comment]
I would try bumping up the base resolution to at least 128 on both unets. Maybe you play around with the channel multipliers if you're running out of memory, you don't necessarily have to use [1, 2, 3, 4] or [1, 2, 4, 8].

**Comment by ken012git** [comment]
I see. Let me try with smaller cascade Unet first.
In my experiment, 64 and 128 can be trained pretty well by using only one Unet, but we can still try 64->128 cascade version for debugging.

**Comment by marunine** [comment]
Looks like a bug snuck in for the in/out dimensions on the upscaling path:

https://github.com/lucidrains/imagen-pytorch/blob/14684fae92fe523ff6c83ac639b8d1d81356430b/imagen_pytorch/imagen_pytorch.py#L1117

Should be `up_in_out_slice:`, missing the colon I think.

**Comment by marunine** [comment]
Some things I did notice when reviewing the OpenAI Unet code vs this one/Google's is that the OpenAI one does the Upsample at the end, like the efficient Unet already does. So I think that's fine to leave as-is without a memory efficient option changing the ordering.

For attention it looks like OpenAI does Attention after every ResNet, but Google seems to do it after all the ResNetBlocks in the Efficient Unet. For the base Unet I kind of wonder if it's still following what OpenAI was doing for that base 64x64 Unet, however.

Google seems to use kernel_sizes of `(3, 3)` everywhere instead of the `(4, 4)` in the Upsample/Downsample operations in the code right now though.

**Comment by lucidrains** [comment]
@marunine hey! so on thinking about the upsample blocks and questioning why i had that conditional slicing, i realized i may have had an error. i was not concatting the highest resolution feature map as a residual in the memory inefficient version 🤦 . i went ahead and put in a fix for that, but i think i need to refactor the unet altogether at some point. will also need to sit down and read a few unet papers to understand all the possible designs out there. thank you for all this discussion leading up to the bug finds!

for attention, still not too concerned as usual. most papers have shown that placing attention at the end of a chain of convolutional blocks is optimal. it is probably safe to stick with that, and i can introduce a few more attention tricks of my own when i find inspiration

the kernel size of 4 is something i inherited from my earlier work with GANs, but truth be told, probably will make negligible difference whether it is 3 or 4. it won't hurt, that i am certain!

**Comment by marunine** [comment]
Thanks for the clarifications, it helps since I probably haven't read as many papers in this domain as you have!

I think there might still be some bugs with that slicing after I was reviewing at again since I left my comment. At some point it might be easier to just ignore the slicing altogether and cut out that ResBlock at the end to respect all the configuration operations present. I think as it is now you're not getting the correct number of ResBlocks / attention args for that final one in the upsample pass.

Might be easier to just do the group norm -> swish -> conv2d directly and pull that out of that final one.

**Comment by lucidrains** [comment]
@marunine haha, i don't really know much outside of attention and transformer architectures :zany_face: very T-shaped knowledge, as they say

i've accounted for the missing upsampling block in the latest version! :pray: thank you and @Netruk44 and others for this dialogue. it was immensely helpful

**Comment by ken012git** [comment]
Hi,

As mentioned, the code should work very fine with one Unet and generate 64x64 and 128x128 images with good quality (just eyeballing). I just found cascade unet 64->128 could not reach the quality and have the same tinting problem. I think there is some issues in cascade conditioning and augmentation

**Comment by lucidrains** [comment]
@ken012git so i think your dimensions are too small for the super resoluting unet. try upgrading to `dim = 64` or `dim = 128`

also, you'll want to use a linear noise schedule (so `beta_schedules = ('cosine', 'linear')`) as that was their configuration in the paper

**Comment by ken012git** [comment]
Oh thanks, I am trying that.

I seems strange to me that one small Unet can do 128x128 but we have to use two larger unets  for the 64->128 cascade version.

**Comment by marunine** [comment]
I've started retraining the 64x64 unet with the memory efficient architecture as a test and evaluation of the latest changes and they're looking even better after 2 epochs than they did at 30 with the old one. The paper's claim of better convergence looks true, but I also don't why they didn't use it for the 64x64 base one yet.

That missing upsample in the earlier variant in this repo would seem responsible for a lot of the fine details that the model churned trying to produce.

**Comment by marunine** [comment]
One note about the change to diffusion schedule: per the paper (section `F.2`) they still use cosine for that 64->256 Unet, but they do use linear (section `F.3`) for the 256->1024 Unet. You might want to modify the defaults to match that, but I'm not sure how much it matters.

That kind of makes me wonder how useful the full range of aug_level being 0.0 - 1.0 actually is for the upscalers, though. It's probably wasting some amount of network capacity if it has to try and predict from nearly pure noise when you're using an aug_level closer to 0.3 most of the time.

**Comment by deepglugs** [comment]
There's definitely some color tinting going on in the latest (0.5.0) upscaler unet.
![image](https://user-images.githubusercontent.com/70453896/174103963-84477c34-d04a-43d0-a86c-337f14baf161.png)

**Comment by deepglugs** [comment]
unet1 seems fine.  It's just unet2 where I see color shifting.  I'm also using p2_loss_weight=1.0.

**Comment by marunine** [comment]
Is that with `memory_efficient=True` as well on the second Unet?

**Comment by deepglugs** [comment]
> Is that with `memory_efficient=True` as well on the second Unet?

No.  Using the default memory_efficient=False.

**Comment by ken012git** [comment]
> memory_efficient=True

Cool, I will try that in cascade unet.

**Comment by lucidrains** [comment]
> One note about the change to diffusion schedule: per the paper (section `F.2`) they still use cosine for that 64->256 Unet, but they do use linear (section `F.3`) for the 256->1024 Unet. You might want to modify the defaults to match that, but I'm not sure how much it matters.
> 
> That kind of makes me wonder how useful the full range of `aug_level` being `0.0 - 1.0` actually is for the upscalers, though. It's probably wasting some amount of network capacity if it has to try and predict from nearly pure noise when in inference it's using an `aug_level` closer to `0.0 - 0.3`,

ohh yes, you are right (again)

i've made the changes to the default in the latest :pray:

**Comment by lucidrains** [comment]
> unet1 seems fine. It's just unet2 where I see color shifting. I'm also using p2_loss_weight=1.0.

hmm, do you think it could be the p2 loss on the upscaler unet? i made it so p2 loss weight gamma can be configurable

**Comment by lucidrains** [comment]
@deepglugs ok try https://github.com/lucidrains/imagen-pytorch/commit/490c6e7854193102a71d738b7f8c0e15073c02da#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R930 , i've also turned off the skip connection scaling for the final resnet block (and may remove that block altogether at some point), in the case it has anything to do with it

**Comment by deepglugs** [comment]
Trying the latest.  Does it matter if I use memory_efficient=True or not?  With "memory_efficient=True", I'm seeing a green color shifting.  I will try with mem*=False just to be rule that out.

**Comment by lucidrains** [comment]
@deepglugs i don't think it should make any difference

if you are still seeing color shifting, the only thing i can think of is the scaling of the resnet skip connections https://github.com/lucidrains/imagen-pytorch/commit/6b42e37710b43e3d651d0b76676cb9a332f3db7b#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R965 you can try turning that off and see if it helps

**Comment by jacobwjs** [comment]
Jumping in here as I'm seeing similar behavior with tinting and poor results coming out of up-scaling cascade. Trying to hone in on the particulars, and have some thoughts,

1. Unet (unet_number = 1, lowest resolution) should have the largest capacity in the cascade to maximize sample quality (empirically demonstrated). I've seen somewhere (perhaps on discord) the opposite configuration. You can typically get away with halving capacity of Unet-2 if Unet-1 is sufficiently large.
2. Overly noised low-res conditional image would degrade fidelity I'd assume. I believe Ho et al. showed this.

It seems most have bumped up Unet-1 capacity, which satisfies point 1., so now assuming the Unet themselves function correctly (efficient or non), which seems to be the case as the low-res version for most is functioning as expected, the next logical step is what's happening with the low-res conditional image to the rest of the cascade.

Has anyone tried a simple Guassian blur as a sole augmentation of low-res conditional image? 

Also configurations/datasets seem all over the place. It would be great to standardize on a dataset, loss function, batch size, T5 model, etc until this gets sorted. Seems like a lot of rather random poking around. We could get to a solution much quicker if we were a bit more aligned and testing in parallel. 

Perhaps even syncing to a shared W&B?

**Comment by jacobwjs** [comment]
> @deepglugs i don't think it should make any difference
> 
> if you are still seeing color shifting, the only thing i can think of is the scaling of the resnet skip connections [6b42e37#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R965](https://github.com/lucidrains/imagen-pytorch/commit/6b42e37710b43e3d651d0b76676cb9a332f3db7b#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R965) you can try turning that off and see if it helps

Why not something akin to instance normalization?

**Comment by jacobwjs** [comment]
> so i think, for the super-resoluting unets, i am going to add one more residual, this one right from the output of the initial conv to just before the final output conv. that should give it enough information to not shift around

I'm not following. Why would that bound the channel min/max values to the appropriate ranges?

**Comment by jacobwjs** [comment]
Was thinking of a simple, low-res, widely available dataset to use to figure out the tinting issue and I think good old MNIST fits here. Single channel that can be repeated to form a "color" (i.e. rgb) image. This would remove any possibility of the network having to learn tint/color and any artifacts can be solely a point of the network. It's super tiny so should be able to pick a batch size that can fit across a variety of compute without hitting OOM. Just need some supporting text/image pairs, which can be formed from something like:


```
mnist_mapping = ['a ', 'an image of a ', 'photo of the number ', 'the number ']


label_mapping = {
    "0": ["zero", "0"],
    "1": ["one", "1"],
    "2": ["two", "2"],
    "3": ["three", "3"],
    "4": ["four", "4"],
    "5": ["five", "5"],
    "6": ["six", "6"],
    "7": ["seven", "7"],
    "8": ["eight", "8"],
    "9": ["nine", "9"],
}


def collate_mnist_fn(data):
    image, label = zip(*data)
    image = torch.stack(image, dim = 0)
    image = repeat(image, 'b c h w -> b (repeat c) h w', repeat = 3)
    
    text = []
    for idx, label_val in enumerate(label):
        number_list = label_mapping[str(label_val)]
        number = number_list[np.random.randint(0, len(number_list))]
        
        # Form the final text sentence.
        #
        sentence = mnist_mapping[np.random.randint(0, len(mnist_mapping))] + number
        text.append(sentence)
    
    return image, text
    

image_size = 64


transform = transforms.Compose([
    transforms.Resize((image_size, image_size)),
    transforms.CenterCrop(image_size),
    transforms.ToTensor()
])


dataset = torchvision.datasets.MNIST(
    root = "/your/local/datapath/MNIST",
    train = True,
    download = True,
    transform = transform,
)
```

**Comment by ken012git** [comment]
Hi,
I tried to train with v0.6.5 yesterday and I found tinting problem is alleviated, but not sure why.

I have tried both dim=128, dim=32 for cascade unets. However, the sampling images are still blurry for current steps (100k).

My configuration:
```
    unet1 = Unet(
        dim = 128,
        cond_dim = 512,
        dim_mults = (1, 2, 4, 8),
        num_resnet_blocks = (2, 2, 2, 2),    # small
        layer_attns = (False, False, False, True),
        layer_cross_attns = (False, False, False, True),
        use_linear_attn = False,
        memory_efficient=True,
    )
    unet2 = Unet(
        dim = 128,
        cond_dim = 512,
        dim_mults = (1, 2, 4, 8),
        num_resnet_blocks = (2, 2, 2, 2),    # small
        lowres_cond = True,
        layer_attns = (False, False, False, True),
        layer_cross_attns = (False, False, False, True),
        use_linear_attn = False,
        memory_efficient=True,
    )
    imagen = Imagen(
        condition_on_text = False,   # this must be set to False for unconditional Imagen
        unets = (unet1, unet2),
        image_sizes = (64, 256),
        timesteps = 1000,
        auto_normalize_img = False,
        continuous_times = True,
        p2_loss_weight_gamma = 1,
    )
```

**Comment by lucidrains** [comment]
i'm really sorry, but i introduced a bug yesterday when i brought in the global context (squeeze excite) module

fixed in 0.7.1, and also added a few more things (learned sinusoidal pos emb that Katherine has in her repositories)

**Comment by lucidrains** [comment]
@ken012git i think i will just add the gaussian blur as an option, if we can't get this new low res noise augmentation working well

**Comment by ken012git** [comment]
Sure, thanks for your implementation. Let me try v0.7.1

**Comment by lucidrains** [comment]
> > so i think, for the super-resoluting unets, i am going to add one more residual, this one right from the output of the initial conv to just before the final output conv. that should give it enough information to not shift around
> 
> I'm not following. Why would that bound the channel min/max values to the appropriate ranges?

your intuition is as good as mine, but my thought is that the unet can compare the output with the initial feature map and decide where the noise is through a quick comparison. i've also added further time conditioning at the last step in the latest commit

perhaps an extra squeeze excitation is in order (so it can adjust things based on the channel-wise statistics)

**Comment by lucidrains** [comment]
@jacobwjs  @ken012git Ken reports the tinting has improved a bit, so maybe it worked!

**Comment by lucidrains** [comment]
@jacobwjs yea, if you are able to rally the researchers in the discord to do some organized experimentation, more power to you

my experience is that it can be a bit like herding cats, but ymmv

**Comment by lucidrains** [comment]
@ken012git i'll wait for your (and other's results) if it still isn't that great by end of today or tomorrow, i can bring in the gaussian blur with the same noise-level conditioning scheme (which has been further proven out by Tero Karras in his paper)

**Comment by lucidrains** [comment]
i think we are close to defeating the final problem, just have to deal it a few more blows

**Comment by ken012git** [comment]
> @jacobwjs @ken012git Ken reports the tinting has improved a bit, so maybe it worked!

Sorry I just don't have time to trace all versions (you implement it too fast  :p ). Just wondering what have you changed and what might cause the tinting issue? I guess that is something to do with noise augmentation?

**Comment by marunine** [comment]
I'm still training some older models as well, but before I switch over to the latest stack of changes I was doing some review and spotted some more potential bugs.

Per the paper, Section D.3.1 they implement cross attention by concatenating the text embedding sequence to the key-value pairs of each self-attention layer in the base 64 x64 and 256 x 256 models. For the 1024 x 1024 they add explicit cross-attention layers. These are all after the ResNetBlocks instead of within as stated before.

I believe you when you say that more attention doesn't hurt here, but I don't think the conditioning is actually getting passed to the resnet blocks:

https://github.com/lucidrains/imagen-pytorch/blob/ccf848cfd1f8306e654112d61e95376180a67a90/imagen_pytorch/imagen_pytorch.py#L1370

https://github.com/lucidrains/imagen-pytorch/blob/ccf848cfd1f8306e654112d61e95376180a67a90/imagen_pytorch/imagen_pytorch.py#L1390

https://github.com/lucidrains/imagen-pytorch/blob/ccf848cfd1f8306e654112d61e95376180a67a90/imagen_pytorch/imagen_pytorch.py#L661

Nor does it look like the time_emb makes it in. I am understanding this correctly?

**Comment by marunine** [comment]
Maybe it's intentional, actually.  I see no cond_dim/time_embeds for those inner layers that are multiplied by the num_resnet_blocks, but it does make it into that initial resnet block. The only thing that would really be missing is the concat onto the transformer block in the self attention like the paper does.

Sorry for the false alarm.

**Comment by lucidrains** [comment]
@marunine yea, so i actually wasn't sure whether the stack of resnet blocks receive any conditioning or not, time or text

my take from the diagram is that the conditioning only comes at the beginning of each downsampling and upsampling block

i think i could do some improvisation and have it efficient condition throughout the whole stack though

**Comment by lucidrains** [comment]
@marunine  haha, you edited your post at the same time i posted :laughing:

**Comment by lucidrains** [comment]
@marunine @ken012git how is it looking? do i need to bring in the gaussian blur from the original cascading ddpm paper?

**Comment by deepglugs** [comment]
My run from last night using 0.7.2 looks pretty good.  Still some slight
discoloration, but otherwise clear.  I'll upload samples here in a bit.

**Comment by lucidrains** [comment]
@deepglugs hurray! yea, i figured - usually silence is a good sign, i've learned working with researchers. they only make a lot of noise when things are broken lmao

**Comment by deepglugs** [comment]
Samples from last night's run (sfw-ified)

![imagen_10_400](https://user-images.githubusercontent.com/70453896/174446946-0ccc3edc-10fc-4168-a266-a49cbe6460e6.png)

**Comment by lucidrains** [comment]
@deepglugs ok, i don't want to know what you are training on, but that looks good lol

**Comment by lucidrains** [comment]
@deepglugs hmm, still a slight tint, from sepia towards bluish

**Comment by deepglugs** [comment]
Trying to leverage datasets I already have.  Wanted to see how good of face detail I could get and well... this is the best dataset I have for that.  Also doing deepfashion and trying to use pose estimation as an additional input to the text embed (or in this experiments replace the text embed), but things are nearly as crisp on 0.6.5.

![imagen_33_56](https://user-images.githubusercontent.com/70453896/174447092-946b2087-f6d5-467f-8fee-5b550d81f45d.png)

**Comment by lucidrains** [comment]
@deepglugs yea, it would be nice to be able to condition on an image (or multiple images, leading frames of a video etc) i'll think about it after i finish the Imagen training code

**Comment by deepglugs** [comment]
I'd love to hear your take on it.  My idea was to just use vgg19 to get a 1024 array and append to the text_embed.  However, there's obviously something wrong with my thinking.

**Comment by lucidrains** [comment]
@deepglugs yup, in addition to your way (+ clip image encoding), the way everyone is doing it is simply resize the condition (pose picture) and concat it to the image being denoised along the channel dimension. so basically like the augmented low-resolution conditioning in the second and third unets

**Comment by lucidrains** [comment]
for video, you just concat a few more images, and during time attention, you can specify the relative positions of each frame through your favorite relative positional encoding scheme

**Comment by lucidrains** [comment]
@deepglugs eventually i think we will get latent diffusion working well for the first unet of the cascade, and that should make pose estimation conditioning work better than working in pixel space.

**Comment by marunine** [comment]
My results mostly align with the ones above. I don't find global tinting, but I do see that images that had white backgrounds tend to shift towards a different color entirely in the second unet.

I'm not really sure what causes that - maybe it's the dynamic thresholding? I don't see many examples from Google's results that look like stock images or have _any_ white backgrounds.

Looking at Figure A.8 supports this, where there's the sample that has a purely white background but all the dynamic threshold samples have a gray or blue.

**Comment by lucidrains** [comment]
@marunine yeah i thought about that

do you think it is worth having some setting to turn off dynamic thresholding some steps into the sampling process? (in favor of just normal clipping? or perhaps turn off classifier free guidance after X number of sampling steps)

**Comment by lucidrains** [comment]
i also wonder if classifier free guidance is even really necessary past the first unet

**Comment by marunine** [comment]
Per unet guidance settings is probably an interesting experiment. I think you'd still want to guide it somewhat since you have the conditioning on at least the 256x256 layer.

A dynamic schedule for the dynamic thresholding sounds like it might be challenging to finetune though - but that's the sampling stage, so it's a lot quicker than playing around with once you have a trained model.

**Comment by lucidrains** [comment]
does dalle2-pytorch have this problem?

**Comment by lucidrains** [comment]
yea, i think for starters i'll just make it so dynamic thresholding can be turned on / off per-unet

**Comment by lucidrains** [comment]
https://github.com/lucidrains/imagen-pytorch/commit/c445f0706d469643f9434a1aade0f9077dc7f653

```python
Imagen(
  dynamic_thresholding = (True, False, False)  # only first unet has dynamic thresholding
)
```

**Comment by marunine** [comment]
I haven't played around too much with the dynamic thresholding yet, but I've still been wondering about the final convolution of the Unet.

The OpenAI one has it do a Conv2D with `kernel size = 3` and `padding = 1`, but the kernel size for the one in this repo is `1`:

https://github.com/lucidrains/imagen-pytorch/blob/c445f0706d469643f9434a1aade0f9077dc7f653/imagen_pytorch/imagen_pytorch.py#L1194

In the Imagen paper they use a Linear layer out in Figure A.30 for the efficient Unet.

I wonder if that's worth exploring on the output? Locally I've seen better results with color on the output by changing the kernel/padding size on the Conv2d to match the OpenAI one. I haven't tried playing around with replacing it with a Linear layer instead yet.

I think a Linear replacing the final ResNet block + Conv might be an interesting experiment at least.

**Comment by lucidrains** [comment]
so a Conv2D of kernel size 1 is actually equivalent to a Linear, so it comes down to whether the final resnet block is necessary or not

i can add the option to change the kernel size of the final conv (with padding to make sure output is the same)

**Comment by lucidrains** [comment]
https://github.com/lucidrains/imagen-pytorch/commit/17737ef3968f7a5890838e87d014ca7bc7711643 for the conv kernel size, do share your results (positive or negative) if you redo your experiments :smile:

**Comment by lucidrains** [comment]
@marunine and finally an ability to turn off the final resnet block https://github.com/lucidrains/imagen-pytorch/commit/40c8a69c1eadd729d26fe9d3a1687f58f727de99#diff-edef3c5fe92797a22c0b8fc6cca1d57b4b84ef03dfdfe802ed9147e21fc88109R992 just so we get to the bottom of this!

**Comment by lucidrains** [comment]
@deepglugs let me know how your pose conditioning generation goes! https://github.com/lucidrains/imagen-pytorch/commit/b2323c1d15a29950becbe5911a5f4e49c90c4492

**Comment by deepglugs** [comment]
Oh nice!  I'll open up a new "issue" when I have results :).

**Comment by deepglugs** [comment]
This training was seeing discoloration earlier, but it has gone away.

 ![imagen_28_60](https://user-images.githubusercontent.com/70453896/174506183-19acbde2-98bc-4142-be01-3a3d1957464d.png)

**Comment by lucidrains** [comment]
> This training was seeing discoloration earlier, but it has gone away.
> 
> ![imagen_28_60](https://user-images.githubusercontent.com/70453896/174506183-19acbde2-98bc-4142-be01-3a3d1957464d.png)

yay! which version of imagen-pytorch is this?

**Comment by deepglugs** [comment]
Probably 0.7.2... but I'm rerunning it with 0.8.0 now.

**Comment by lucidrains** [comment]
ok, i think this is resolved

**Comment by oconnoob** [comment]
According to the pseudocode linked by @marunine, which is the reasoning for using a single augmentation time, wouldn't we also need to use one timestep value for every image in the high resolution batch? [Currently](https://github.com/lucidrains/imagen-pytorch/blob/176bd55ed5b9b499779281adb7f18fcabe1b4036/imagen_pytorch/imagen_pytorch.py#L2102) we select a different time for each image in the batch.

Maybe I'm misunderstanding, in which case clarification would be greatly appreciated! Thanks

(pseudocode again for convenience)
``` python
def train_step(
  x_lr: jnp.ndarray, x_hr: jnp.ndarray):

  # Add augmentation to the low-resolution image.
  aug_level = jnp.random.uniform(0.0, 1.0)
  x_lr = apply_aug(x_lr, aug_level)

  # Diffusion forward process.
  t = jnp.random.uniform(0.0, 1.0)
  z_t = forward_process(x_hr, t)

  Optimize loss(x_hr, nn(z_t, x_lr, t, aug_level))
```

**Comment by XavierXiao** [comment]
> deepglugs

Are you predicting x_0 or noise for the SR? I still have the color shift issue.
