### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Huyuxuan-github** [lucidrains/imagen-pytorch#59]
Could you please tell us how to use this project in detail in the readme.md? I could not run the code correctly.

**Comment by prashantkandel12** [comment]
you could try colab notebook as mentioned [here](https://github.com/lucidrains/imagen-pytorch/issues/24)

**Comment by Huyuxuan-github** [comment]
> you could try colab notebook as mentioned [here](https://github.com/lucidrains/imagen-pytorch/issues/24)

thank you for answering, I will turn to that notebook to have a try.
