### ISSUE TITLE
text_embeds size?

### ISSUE THREAD

**Issue by nagolinc** [lucidrains/imagen-pytorch#60]
In the readme line 59, text embeds appear to be shape (ntexts, 256, 768).  But on line 146 they are shape (ntexts,256,1024).  And the output of t5_encode_text appears to be (ntexts,ncharacters,768).

Which is correct?  It seems like I can just tile along dimension 1 to pad out to 256, but what is the correct value for dimension 2?

**Comment by deepglugs** [comment]
I see (batch, n, 1024) in my experience where n can be small (around 7) or as large as 256 as you've noted.

**Comment by fauzanardh** [comment]
For dim 2, it depends on which encoder you use:
- t5-small -> 512
- t5-base -> 768
- t5-large -> 1024
