### ISSUE TITLE
Training on SVHN Dataset

### ISSUE THREAD

**Issue by Preethse** [lucidrains/imagen-pytorch#61]
Hello, Thanks for coming up with the code. I was trying to training SVHN dataset(http://ufldl.stanford.edu/housenumbers/) with images of number and txt file containing the number itself. Even after 50 epochs of training the result I get is just some random noise. So my questions are
1) Is it possible to generate samples of SVHN dataset through this kind of training.
2)Is yes, do you think I need to add some additional information to this model.

Thanks

**Comment by MarlNox** [comment]
Sounds feasible if the input dataset provides all the input dynamics. 
Also from what i've seen in the LAION discord, the model seems to be a bit dyslexic and may produce weird (albeit not always) results when it comes to characters/numbers.

**Comment by LetterRip** [comment]
> Sounds feasible if the input dataset provides all the input dynamics. Also from what i've seen in the LAION discord, the model seems to be a bit dyslexic and may produce weird (albeit not always) results when it comes to characters/numbers.

Probably doing augmentation with left-right flipping, but the description is the same so it thinks reversed words/characters/numbers are the same forwards and backwards.
