### ISSUE TITLE
Mac M1 / MPS workaround?

### ISSUE THREAD

**Issue by joshstrike** [lucidrains/imagen-pytorch#68]
Has anyone successfully run Imagen on Apple Silicon? Having changed the `.cuda()` calls in the example to `.to('mps')`, it seems some of Imagen's Torch calls are still unsupported, including `aten::bitwise_and.Tensor_out`. Torch wants to fallback to CPU if I set PYTORCH_ENABLE_MPS_FALLBACK=1 but I then the `imagen()` call throws the error that `indices should be either on cpu or on the same device as the indexed tensor (cpu)`. I assume this is due to the fallback. Is there any workaround at the moment?

**Comment by Raymonf** [comment]
Unfortunately, the MPS backend is still incomplete. https://github.com/pytorch/pytorch/issues/77764 is tracking missing operators.

**Comment by takaria0** [comment]
Yes, I also encountered this issue `The operator 'aten::_index_put_impl_' is not current implemented for the MPS device.`.  I'm not sure how faster using `mps` device is though.

**Comment by lucidrains** [comment]
i don't think this will be supported for a while unfortunately
