### ISSUE TITLE
Pytorch DirectML support

### ISSUE THREAD

**Issue by TheProtaganist** [lucidrains/imagen-pytorch#70]
I love to see all the hard work you and other developers are putting into these models, though I was wondering why do they all need cuda to run? I have a Intel UHD 620 graphics card and I was wondering if it is possible to make imagen-pytorch be compatible with pytorch directml so people with Intel gpus can run it too! Training models on cpus is hard and I would love to see more models compatible with Intel and direct ml, thank you so much in advanced

**Comment by lucidrains** [comment]
probably won't support this edge case
