### ISSUE TITLE
Poor output

### ISSUE THREAD

**Issue by krrishdholakia** [lucidrains/imagen-pytorch#74]
Hi, 

I am using the reference imagen training notebook. 

I found a dataset of ikea room scene images. And am trying to train the model on that. 

But the output I'm getting is incredibly noisy - even after training for 35 epochs. 

![image](https://user-images.githubusercontent.com/17561003/174889248-e17dec92-a1f5-46aa-9ddc-bf843efaa5df.png)

Colab notebook for reference - https://colab.research.google.com/drive/1iyCrYW3_rES95qXA_qwhcVlpwHWVtU_I?usp=sharing

Any help here would be appreciated.

**Comment by krrishdholakia** [comment]
<img width="698" alt="Screen Shot 2022-06-21 at 1 16 27 PM" src="https://user-images.githubusercontent.com/17561003/174889699-def91b6a-2ecf-4ad9-9b6c-31c26e9fd52b.png">
<img width="717" alt="Screen Shot 2022-06-21 at 1 16 47 PM" src="https://user-images.githubusercontent.com/17561003/174889735-17f56264-b74a-4603-95a5-d89890993184.png">

**Comment by lucidrains** [comment]
@krrishdholakia Hi Krish, unfortunately the notebook doesn't load the images correctly

I'll get the CLI tool working soon, just be patient. making it so even your grandparents can train this
