### ISSUE TITLE
Unused parameters in final_res_block in UNet

### ISSUE THREAD

**Issue by sarvghotra** [lucidrains/imagen-pytorch#75]
Looks like there are some unused parameters in the model. The following is an error message that I got from training it in DDP mode:

> Parameters which did not receive grad for rank 14: final_res_block.time_mlp.1.bias, final_res_block.time_mlp.1.weight, norm_mid_cond.bias, norm_mid_cond.weight

On investigating, it seems like the root cause is missing `c` argument to the `final_res_block` [here ](https://github.com/lucidrains/imagen-pytorch/blob/779616405797034d8fccd6ce7fc2e8dc05778088/imagen_pytorch/imagen_pytorch.py#L1428)unless it is not required, in that case, the `time_cond_dim` argument should have been set to `None`.

**Comment by sarvghotra** [comment]
And, the other unused are here: https://github.com/lucidrains/imagen-pytorch/blob/779616405797034d8fccd6ce7fc2e8dc05778088/imagen_pytorch/imagen_pytorch.py#L1094

**Comment by lucidrains** [comment]
@sarvghotra should be all fixed, thank you Sarvjeet!

**Comment by lucidrains** [comment]
@sarvghotra are you using a framework for DDP training or did you roll your own?

**Comment by sarvghotra** [comment]
For now, I am just trying to use Pytorch's DDP. If I got some good initial results, will move to DeeepSpeed.

**Comment by lucidrains** [comment]
@sarvghotra ok sounds good! i'll proceed with the accelerate or pytorch lightning integration then 😄
