### ISSUE TITLE
Google colab under 24gb?

### ISSUE THREAD

**Issue by ford442** [lucidrains/imagen-pytorch#77]
I just started trying to run this as a Jupyter Notebook and I am trying to raise up the resolution. I can get 128x128 or 192x192, but any higher runs out of VRAM on Colab Pro.
So, what settings might lower GPU memory usage with a reasonable tradeoff?
I want to try to get 320x320 < 448x448 or more resolution..

I keep getting like "Attempted to allocate 29gb, using 8gb for pytorch, 7gb reserved, 14gb total" When current Colabs have an Nvidia M6000 with 24gb..

**Comment by lucidrains** [comment]
@ford442 there is one paper queued up in my reading list that could help https://arxiv.org/abs/1906.06148 we can keep this open and if the paper applies, then turn it into some actionables

**Comment by LetterRip** [comment]
Here are git repositories associated with the above paper,

https://github.com/RobinBruegger/RevTorch

https://github.com/RobinBruegger/PartiallyReversibleUnet
