### ISSUE TITLE
SRUnet256 Constructor overwrites all parameters in "Imagen without text" example

### ISSUE THREAD

**Issue by FriedrichM** [lucidrains/imagen-pytorch#79]
In the "Imagen without text" example from the README the second Unet is created with these parameters

```
unet2 = SRUnet256(
    dim = 32,
    dim_mults = (1, 2, 4),
    num_resnet_blocks = (2, 4, 8),
    layer_attns = (False, False, True),
    layer_cross_attns = (False, False, True)
)
```

But all of them are overwritten by the SRUnet256 constructor as far as i can tell.

```
class SRUnet256(Unet):
    def __init__(self, *args, **kwargs):
        kwargs.update(dict(
            dim = 128,
            dim_mults = (1, 2, 4, 8),
            num_resnet_blocks = (2, 4, 8, 8),
            layer_attns = (False, False, False, True),
            layer_cross_attns = (False, False, False, True),
            attn_heads = 8,
            ff_mult = 2.,
            memory_efficient = True
        ))
        super().__init__(*args, **kwargs)
```

**Comment by lucidrains** [comment]
@FriedrichM oh yea, i intentionally did that to show researchers that the hyperparameters can still be overridden

if you want the parameters in the paper, removing everything is correct

**Comment by FriedrichM** [comment]
I think setting the hyperparameters like this : 
```
unet2 = SRUnet256(
    dim = 32,
    dim_mults = (1, 2, 4),
    num_resnet_blocks = (2, 4, 8),
    layer_attns = (False, False, True),
    layer_cross_attns = (False, False, True)
)
```
does not work as it makes no difference to this 
`unet2 = SRUnet256() `
because they will be overwritten by the SRUnet256 constructor anyways

my point is you can put whatever you want in there like  
```
SRUnet256(
    dim = "a red cow",
    dim_mults = -1337,
    num_resnet_blocks = ("yes")
) 
```
it has no effect which is misleading in my opinion
you'd have to change the values in the class definition inside imagen_pytorch.py
for it to make a change.

**Comment by lucidrains** [comment]
@FriedrichM :man_facepalming: my bad, thank you! https://github.com/lucidrains/imagen-pytorch/commit/ace031e604618b824d36693d3424c358c2797242
