### ISSUE TITLE
Hiddens and tokens

### ISSUE THREAD

**Issue by VigneshSrinivasan10** [lucidrains/imagen-pytorch#87]
First of all, great work! 

Apologies if this is a very silly question, but it was not immediately clear to me when looking at the code, the difference between `text_tokens` and `text_hiddens` at https://github.com/lucidrains/imagen-pytorch/blob/30744d893a954ef3be4930100686a70d562daecb/imagen_pytorch/imagen_pytorch.py#L1361

It would be great if you could elaborate on why you do this. 
Any pointers on this would also be helpful. 
Thanks in advance.

**Comment by lucidrains** [comment]
@VigneshSrinivasan10 so i'm doing two types of conditioning for text (1) the cross attention based conditioning as in the paper (`to_cond`), but also (2) a time / noise - like conditioning (`to_hiddens`)

**Comment by lucidrains** [comment]
@VigneshSrinivasan10 just extra insurance that the entire network is weakly conditioned by the FiLM / adaptive group norm as is time / noise, but also gets the powerful (but infrequent) cross attention

**Comment by VigneshSrinivasan10** [comment]
@lucidrains Thanks for the explanation. I believe then that this extra insurance may not be essential but could help in some cases where the conditioning may be weak.

**Comment by lucidrains** [comment]
> @lucidrains Thanks for the explanation. I believe then that this extra insurance may not be essential but could help in some cases where the conditioning may be weak.

yea, try ablating it, and do share your results if you see no difference in your work
