### ISSUE TITLE
training on a large dataset

### ISSUE THREAD

**Issue by yli1994** [lucidrains/imagen-pytorch#89]
Hi @lucidrains 
Thank you for your great work!

I am going to train Imagen on a relatively large dataset(100M data, a subset from LAION-5B) with 8xRTX3090  .

For the text-to-image DDPM, 128dim-non-efficient or 256dim-efficient will be considered, can I have your suggestion which one you may prefer(256dim-eff speed is about 2x faster at around 2days/epoch)

Learned a lot from your discussion in issue#72!

**Comment by lucidrains** [comment]
@yli1994 hey! so i think non-efficient is the more conservative route, until we close out issue 72

128 dimension with non efficient should be sufficient, but your guess is as good as mine :laughing:

**Comment by yli1994** [comment]
@lucidrains  thanks! I will try 128 non-eff first, but the speed of 256-eff is so charming😆😆

**Comment by lucidrains** [comment]
@yli1994 definitely chat with Aidan and Zion, they have been training the dalle2-pytorch unet with good results and probably have some tips 😄

**Comment by lucidrains** [comment]
@yli1994 i'll try to get the lightning training code in place by week's end!

**Comment by srelbo** [comment]
Here is our run ~ 90k steps (memory efficient unet) ... No color shifting as far as I can see.. (samples in report)

https://wandb.ai/elbo-ai/imagen/runs/1y5gc6d2?workspace=user-elbo

This is from `v0.11.5` IIRC..

**Comment by camlaedtke** [comment]
@srelbo Great report! Looks like you're starting to get good results. A few questions

-  For your training loop, are you training one unet at a time (i.e. train unet1 for 25 epochs, then train unet2 for 25 epochs, etc.).  Or are you training each unet through all mini-batches once per epoch (i.e. train unets 1 and 2 for one epoch, then train unets 1 and 2 for the next epoch, and so on)?
- How many images does your dataset contain? 
- Have you noticed a pretty big increase in model size and training speed between 0.11.5 and 0.14.1? I definitely have. 

Anyways, I am currently training on a single RTX 3090 GPU on the CocoCaptions dataset. Here's my run so far. 
https://wandb.ai/camlaedtke/imagen?workspace=user-camlaedtke

**Comment by yli1994** [comment]
> @yli1994 i'll try to get the lightning training code in place by week's end!

Sounds great! Looking forward to it!

**Comment by yli1994** [comment]
> * For your training loop, are you training one unet at a time (i.e. train unet1 for 25 epochs, then train unet2 for 25 epochs, etc.).  Or are you training each unet through all mini-batches once per epoch (i.e. train unets 1 and 2 for one epoch, then train unets 1 and 2 for the next epoch, and so on)?

Training one unet at one time could be cheaper. You can respond to your generation results faster and tune your strategy, especially when using few gpus.

**Comment by camlaedtke** [comment]
@srelbo Good to know, thanks! Yeah using a single GPU is really testing my patience. Looks like it'll take a couple of days to train 30,000 steps but hopefully that will be good enough for somewhat decent results.

**Comment by yli1994** [comment]
Hi @lucidrains 
should I wrap my dataloader and trainer instance with accelerator.prepare in my train.py script? When I call accelerate launch my dataloader was not splited into N nodes.
