### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by HartmanAnalytics** [lucidrains/imagen-pytorch#92]
Having venv issues; unsure of proper python version and module versions. Can you please provide guidance on a suitable python version and a requirements.txt?

**Comment by jacobwjs** [comment]
have you `$ pip install imagen-pytorch`?

**Comment by srelbo** [comment]
If you compiled Python3.10 from the source, you would have to do it again after installing:

```
sudo apt-get install lzma
sudo apt-get install liblzma-dev
```

Followed by re-compiling Python3.10 and installing. Here are the complete steps

```
sudo apt install wget lzma liblzma-dev build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev 
wget https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz
tar xzf Python-3.10.2.tgz
cd Python-3.10.2
./configure --enable-optimizations
sudo make altinstall
```
Another option is to use Anaconda, but the former worked for me on Debian.
