### ISSUE TITLE
Conditioning augmentation for low resolution images

### ISSUE THREAD

**Issue by UdonDa** [lucidrains/imagen-pytorch#93]
Hi, @lucidrains 

I have a question about the conditioning augmentation of imagen.
I guess you apply the augmentation [here](https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L1382). But, I do not know your implementation is correct.

Because an Imagen paper does not describe the detail of the augmentation, I think Imagen uses as same as Cascaded diffusion ones(https://cascaded-diffusion.github.io/assets/cascaded_diffusion.pdf).
Your implementation seems to apply a forward process of DDPM to low reso images but does not apply a gaussian blur.
(I know that you implemented to add sigmas of low-resolution images to enable a network to learn them #44 )

Why do you apply no gaussian blur to low-resolution images?

In addition, where do you implement `aug_level`..? I'm sorry that I cannot find it.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/25411643/176986141-17721ce0-02b0-43eb-870c-5a15345794a8.png">

**Comment by lucidrains** [comment]
![Screenshot from 2022-07-02 08-37-57](https://user-images.githubusercontent.com/108653/177007116-d6f5f71a-0241-4634-a854-8ec14f7b88a3.png)

Hi @UdonDa 

So the way they phrased this section of the paper seems to suggest they went with only the gaussian noise, with the augmentation noise level (sigma) as conditioning factor

Notice the word `or`, and then later on `we went with`

**Comment by lucidrains** [comment]
@UdonDa i would be happy to add the gaussian blur though, because i'm wondering if these augmentations can be stacked (gaussian blur and noise) for additional benefits
