### ISSUE TITLE
Unet specific step count breaks loading of existing models

### ISSUE THREAD

**Issue by srelbo** [lucidrains/imagen-pytorch#96]
Hey @lucidrains,

The UNET-specific step count breaks the loading of existing models (in this commit - https://github.com/lucidrains/imagen-pytorch/commit/cbe7d2e9d62b88ef6442335f73d3bc433214a2f5) 

```
  File "/home/joy/projects/imagen-pytorch/imagen_pytorch/trainer.py", line 357, in load
    self.step.copy_(loaded_obj['step'])
TypeError: copy_(): argument 'other' (position 1) must be Tensor, not float
```

This is probably intended, but could we increment the major version in such breaking changes, say -

```
__version__ = '0.18.1'
```

Thanks!

**Comment by lucidrains** [comment]
yea sure, you'll have to live with this one though
