### ISSUE TITLE
A bug in get_time() function

### ISSUE THREAD

**Issue by BIGJUN777** [lucidrains/imagen-pytorch#98]
Hi there.
In [get_time()](https://github.com/lucidrains/imagen-pytorch/blob/cbe7d2e9d62b88ef6442335f73d3bc433214a2f5/imagen_pytorch/imagen_pytorch.py#L290) function, we found you set the the data type as _long int_. However, the noise level here should be _float_ in the _Continuous Times_ situation. Otherwise, the returned data will always be 0. Please check it out.

**Comment by lucidrains** [comment]
@BIGJUN777 oh gosh, this is a really big bug, thank you for identifying this! https://github.com/lucidrains/imagen-pytorch/commit/1e15940f538bc5eb4ca5cd463f57a0b6323d6250
